### ISSUE TITLE
Action link not handled in Cygwin

### ISSUE THREAD

**Issue by QiangF** [anishathalye/dotbot#101]
Hello Sir,
Dotbot fails to make symbolic links in windows Cygwin environment. I am using babun (http://babun.github.io/). 
Is it possible to make it work across platform?
Thank you!

**Comment by nagromc** [comment]
I'm using Dotbot under GNU/Linux platforms, and Cygwin, and it works like a charm. Can you provide a **minimal** example and the logs?

**Comment by QiangF** [comment]
Turn out to be an issue with Anaconda python, it has issues wih the path. Works perfectly when I removed Anaconda from my path.

**Comment by anishathalye** [comment]
Huh, interesting, I wonder why Anaconda Python doesn't work properly…

Well, I'm glad you got this figured out :)
