### ISSUE TITLE
Check target existance before to remove original files

### ISSUE THREAD

**Issue by ael-code** [anishathalye/dotbot#103]
dotbot version: `28959a3f31d8632975de4e18d0a0e47476b5a413 dotbot (v1.9.3)`

When the force option is enable the original files are removed independently from the existence of the relative targets.

Reproducible steps:
- create a file in your home
```touch ~/.will_be_deleted```
- create the configuration files that contains the non existent target
    ```
    cat <<'EOF' > test2.yaml
    - link:
        ~/.will_be_deleted:
           force: true
           path: nonexistent
    EOF
    ```
- run dotbot 
```./install -c test2.yaml```

You will get this output:
```
Removing ~/.will_be_deleted
Nonexistent target for ~/.will_be_deleted : /home/ael/.dotfiles/nonexistent
Some links were not successfully set up

==> Some tasks were not executed successfully
```

The original file ```~/.will_be_deleted``` has been deleted and then, only after that, it found out that the targets specified for that file was not existent.

My suggestion is to make some sanity check on the target before to delete the correspondent original file

Note: It will be the same if `~/.will_be_deleted` it would be a folder

**Comment by anishathalye** [comment]
Fixed in b482cbda585848c0d5f5345711fe338e319c0adf. Thanks for reporting the issue!

**Comment by ael-code** [comment]
I think that we still have some problem. I mean the problem is fixed but now we have really confusing logs:

If I try to reproduce the bug with the new 1.9.4 version that includes https://github.com/anishathalye/dotbot/commit/b482cbda585848c0d5f5345711fe338e319c0adf you get the following log:
```
~/.will_be_deleted already exists but is a regular file or directory
Some links were not successfully set up

==> Some tasks were not executed successfully
```
The logs should inform the user that is trying to link to an non-existent target. But instead we've got an `already exists` error, even if we are setting  the force variable to true.

**Comment by ael-code** [comment]
with PR #107 the logs will be:

```
Skipping nonexistent target "~/.will_be_deleted" -> "nonexistent"
Some links were not successfully set up

==> Some tasks were not executed successfully
```

**Comment by anishathalye** [comment]
Good catch!
