### ISSUE TITLE
[Request] - Maintain a changelog

### ISSUE THREAD

**Issue by dsifford** [anishathalye/dotbot#108]
Hi there.

Love the project. You've probably saved me a collective year of time/headache, so thank you so much for that. 

I'm wondering if you might be willing to maintain a changelog for this project? It would be nice to be able to come to the repo when new releases are made and quickly see what's changed without diving into the commit history.

Thanks so much either way

**Comment by anishathalye** [comment]
Sure, sounds doable. I think it'll (more or less) be a mirror of commit history, but if it's helpful, it shouldn't be too much effort.

I'll add a changelog on the Wiki and add a link to it from the main repo.

Though this is probably not going to happen for a month or so cause I'm pretty busy. I'll come back to this ~ Dec 20.

**Comment by anishathalye** [comment]
Woo, done! https://github.com/anishathalye/dotbot/wiki/Changelog
