### ISSUE TITLE
Source other configurations in a configuration

### ISSUE THREAD

**Issue by vsund** [anishathalye/dotbot#109]
Is it somehow possible to source configuration files in other ones? What I have in mind: Having a sub directory with a config file for every program and then sourcing them in a more general one for installing them as whole.
Then it would be possible to install the dotfiles of a particular program separately (i.e. with `./install --program <name>`.

Or would it be better to put that logic completely into the `install` script?

**Comment by anishathalye** [comment]
It's not possible to source configuration files in other ones. You could probably put that logic in the install script, kind of like [this](https://github.com/anishathalye/dotbot/wiki/Tips-and-Tricks#how-can-i-have-different-groups-of-tasks-for-different-hosts-with-different-configurations).

**Comment by anishathalye** [comment]
Going to assume this is resolved; feel free to reopen if not.

**Comment by vsund** [comment]
Yeah, sorry for not answering earlier. Wanted to finish my repository and then post it here.
I wrote configuration files for each program group and then edited the `install` script to recognize profiles.

Will post here again when finished the repo.

**Comment by anishathalye** [comment]
Oh, cool! If you have time, it would be awesome if you could add to the [Tips and Tricks](https://github.com/anishathalye/dotbot/wiki/Tips-and-Tricks) page of the Wiki.

**Comment by vsund** [comment]
I added a [description / walkthrough](https://github.com/anishathalye/dotbot/wiki/Tips-and-Tricks/8eddafa00aa06a4c5e76190b979d110cde862f1e#more-advanced-setup) to the wiki.

I tried to keep it precise and short but it's pretty convoluted though. Maybe it's time to split the wiki page for tips & tricks?

**Comment by anishathalye** [comment]
Thanks for the contribution, the information looks good!

Yeah, maybe that page is getting a little big -- a table of contents would be nice. If someone wants to reorganize it, that would be great. Otherwise I might get to it eventually.
