### ISSUE TITLE
argparse and yaml modules missing on CentOS 6.8 (yeah, really)

### ISSUE THREAD

**Issue by zamber** [anishathalye/dotbot#110]
.dotfiles git:(master) ✗ rpm --query centos-release
    centos-release-6-8.el6.centos.12.3.x86_64
    .dotfiles git:(master) ✗ ./install 
    Submodule 'dotbot' (https://github.com/anishathalye/dotbot.git) registered for path 'dotbot'
    Initialized empty Git repository in /home/zamber/.dotfiles/dotbot/.git/
    remote: Counting objects: 538, done.
    remote: Total 538 (delta 0), reused 0 (delta 0), pack-reused 538
    Receiving objects: 100% (538/538), 132.34 KiB, done.
    Resolving deltas: 100% (274/274), done.
    Submodule path 'dotbot': checked out '847cb101d486319da882f958b1cb58b515cc6db2'
    Traceback (most recent call last):
      File "/home/zamber/.dotfiles/dotbot/bin/dotbot", line 23, in <module>
        import dotbot
      File "/home/zamber/.dotfiles/dotbot/dotbot/__init__.py", line 1, in <module>
        from .cli import main
      File "/home/zamber/.dotfiles/dotbot/dotbot/cli.py", line 3, in <module>
        from argparse import ArgumentParser
    ImportError: No module named argparse

after installing argparse:

    .dotfiles git:(master) ✗ ./install                       
    Traceback (most recent call last):
      File "/home/zamber/.dotfiles/dotbot/bin/dotbot", line 23, in <module>
        import dotbot
      File "/home/zamber/.dotfiles/dotbot/dotbot/__init__.py", line 1, in <module>
        from .cli import main
      File "/home/zamber/.dotfiles/dotbot/dotbot/cli.py", line 4, in <module>
        from .config import ConfigReader, ReadingError
      File "/home/zamber/.dotfiles/dotbot/dotbot/config.py", line 1, in <module>
        import yaml
    ImportError: No module named yaml

It's easy enough to `sudo yum install python-{module}` but you can't call it self-contained when modules are missing ;).

**Comment by anishathalye** [comment]
So Dotbot supports Python 2.7+ and Python 3+. argparse is shipped with Python 2.7+ ([see also](https://github.com/anishathalye/dotbot/issues/17#issuecomment-78535370)). I'm not sure if there's any reasonable way to support Python 2.6 and earlier (ideas welcome).

The YAML issue shouldn't be happening… Dotbot includes pyyaml as a submodule ([see here](https://github.com/anishathalye/dotbot/tree/master/lib)), `./install` makes sure the submodule is fetched ([see here](https://github.com/anishathalye/dotbot/blob/master/tools/git-submodule/install#L12)), and we add the right version of the library depending on your Python version ([see here](https://github.com/anishathalye/dotbot/blob/master/bin/dotbot#L12)). Any idea where this is going wrong? (if you `cd` to `lib/pyyaml`, do you see anything there?)

**Comment by zamber** [comment]
the pyyaml module is in `lib/pyyaml`. I removed the module I installed to reproduce it and now it works. Overall everything was wonky during the initial installation and now it's stable. Other than the argparse thing it seems to work pretty well.

As for argparse I can't find an easy nor standard way to have it pulled in dynamically. All I can suggest is bundling it along and doing a conditional import, but then I'm not sure if it's not better to require users with python 2.6 to just install it. In the latter case a `log.warning` and a premature exit would be nice.

Either ways I solved my problems, looks like this was already reported and thought through so I'm closing this issue. Sorry for the trouble ;).

**Comment by anishathalye** [comment]
Huh, I wonder why the pyyaml thing didn't work initially...

Glad you got it working!

**Comment by flyingchipmunk** [comment]
I know this issue is closed, but I wanted to share this incase others googl'ing finds them here.

I needed to deploy dotbot on a cluster of machines where python2.6 is all I've got so I whipped up this '[dotbot-deps](https://gitlab.com/flyingchipmunk/dotfiles/blob/master/dotbot-deps)' script and I call it in my 'install' file.

It's not perfect, but it fits my needs and might help others.
