### ISSUE TITLE
Need some clarification on `clean` command

### ISSUE THREAD

**Issue by dein0s** [anishathalye/dotbot#112]
First of all I want to thank you for this project. Just found it today and in love with it :)
Also, before we continue here, it worth to mention, that english aint my native, so I appologize for any mistakes and misunderstandings in advance.

And now to the point - my question is why
> Only dead links that point to the dotfiles directory are removed.

https://github.com/anishathalye/dotbot/blob/master/plugins/clean.py#L39

Is there any funny story behind this check? Like someone unmounted folder on a prod environment, Dotbot deleted broken link and after remounting folder back - server just crushed?

Seriously, I mean, it seems totally illogicaly for me: we have a dead link, that points to nowhere, and instead of clean/overwrite, we just leave it for the gods of errors during futher installation process.
Like, for example, I've a link ```~/.zshrc_alias -> /dev/null``` that was pointing to some real object in the past, but somehow it's gone now. And... I can't delete it and therefore create a new link that will point to my new file ```~/.dotfiles/.zshrc_alias```.

Just want to understand such implementation before I'll begin using my patronus on it :D

**Comment by anishathalye** [comment]
Glad you liked the project :)

And no, there's no funny story… the reasoning was that if there was some broken link there that apparently didn't have anything to do with your dotfiles, then maybe we shouldn't touch it, just to be safe.

If you specify `relink = True` (e.g. like [this](https://github.com/anishathalye/dotfiles/blob/master/.install.conf.yaml#L4)), then broken symlinks will still be _overwritten_ (so that'll solve the problem for the example you gave above).

**Comment by dein0s** [comment]
Yeah, ```relink``` will work sor sure. But, suddenly, in multi-profile/multi-config project, it can't be inherited from another config file (```base.yaml``` for example), so I have to specify this in every file.

Would you accept a PR with some changes to logic in ```clean.py``` plugin? Like adding a key ```force``` for the instance?

**Comment by dein0s** [comment]
Also, regarding to this plugin, it was meant that method ```self._clean``` always return ```True```?
https://github.com/anishathalye/dotbot/blob/master/plugins/clean.py#L28

And if so, then why do we need [this](https://github.com/anishathalye/dotbot/blob/master/plugins/clean.py#L24) ```else``` statemend with logging if we'll never reach that point?

p.s. Damn, I'm getting addicted to this thing. Even thinking about to write a plugin for handling metaconfigs :D

**Comment by anishathalye** [comment]
Yes. And I guess that's unreachable code 😛

**Comment by dein0s** [comment]
Question answered :)
