### ISSUE TITLE
[Feature Request] Provide docker support for tests execution

### ISSUE THREAD

**Issue by dein0s** [anishathalye/dotbot#113]
Not sure what else I can write up here. Subj speaking for itself :)

**Comment by dein0s** [comment]
Will provide PR today.

**Comment by anishathalye** [comment]
This looks interesting, but what's the motivation for this? We already have tests running on Vagrant (which I'm pretty sure nobody uses anyways) and also on Travis CI.

**Comment by dein0s** [comment]
> (which I'm pretty sure nobody uses anyways)

Exactly, that's why! :)
Okay now, jokes aside. Docker, in comparison with Vagrant, doesn't depend on VB. It's not always possible to start VB locally. Like, for example, in my case - current workstation right now already running in vm (yeah, yeah.. I know, but I still need that damn win for gaming and for my homies).
So, what's the option here for running tests locally (i work as a qa, testing already in my blood:)) and ensure that everything works fine?
Commit, wait for travis to run it, fix, squash, clean git history.. That's just awful.
And in total - why not? Script doesn't breaks anything (almost no changes made to the original files, execpt from DOTFILES var change) and allow users to have a choice.

**Comment by zamber** [comment]
Docker has massive compatibility issues with host kernels, and non-existent backwards compability.

IIRC you can run vagrant under Windows and you already have VB, so just check out the repo on Win and try testing it there.

**Comment by dein0s** [comment]
First of all it's just a matter of choice. As I've mentioned - this PR doesn't break anything, just adds another option for running tests in a virtual environment. Each solution has it's own pros and cons (like described [here](http://stackoverflow.com/a/16048358) for example). And both test scripts by default designed to be executed in Unix env. 

@zamber looks like you didn't understand my case (and I apologize for this, as english aint my native). My home host is under Windows, in it I run VB with Linux as a workstations for my working needs (code, test and other stuff). So, the scheme with Vagrant will look following: windows -> vb with linux -> vb for vagrant. And yes, this is possible ofc, but such scheme will consume much more resources then I want.

**Comment by anishathalye** [comment]
More lines of code added are more lines of code that need to be maintained going forward, so there isn't nonzero cost.

If Docker is superior to Vagrant, we should _switch_, not have both. But I don't think Docker is strictly better than Vagrant.

**Comment by zamber** [comment]
My point was that you can use Vagrant under Windows, so there's no need for
nesting VMs. Just clone the repo and run the tests after installing Vagrant
on your Windows host. Easier than nesting flaky Docker under a VBox VM.

**Comment by dein0s** [comment]
@anishathalye well, at this stage it is all up to you as a lead maintainer. If you want to stick just to one environment for testing and you prefer Vagrant - the choice is simple.
@zamber I try to keep everything consistent. So, when I write some code under Linux, I don't have to switch to Windows to test it. Anyway, tastes are different and every person has his own approach.

**Comment by anishathalye** [comment]
Okay, let's stick with the Vagrant test setup for now.
