### ISSUE TITLE
Switch to python3

### ISSUE THREAD

**Issue by vvug** [anishathalye/dotbot#118]
Hello,

`dotbot` currently doesn't work on systems where only python3 is installed, as it looks for the `python` binary. This means that dotbot doesn't work out of the box on a modern and minimal system (like a minimal Debian stretch). It's probably time to switch to python3.

**Comment by anishathalye** [comment]
Dotbot is compatible with both Python 2 and Python 3, and it uses `#!/usr/bin/env python` to find your Python.

Does Debian Stretch not have a `python` binary or symlink or anything?

**Comment by vvug** [comment]
@anishathalye thanks for the quick reply. `python` is a symlink a python2.7 interpreter, and exists only if a package providing python2 is installed. It never points to a python3 interpreter.

`/usr/bin/python3` is a symlink to python3.5 (currently), and it's always present in newer Debians.

**Comment by anishathalye** [comment]
Hmm, what's the best way to solve this? We want something that'll use `python` if it's available, otherwise try `python2`, otherwise try `python3`. Or something like that. The order doesn't really matter.

**Comment by vvug** [comment]
I just see two ways:
- Use a wrapper script.
- Just use `python3`. It has been out for like 9 years now.

BTW, Debian does what https://www.python.org/dev/peps/pep-0394/ recommends:
- `python2` will refer to some version of Python 2.x.
- `python3` will refer to some version of Python 3.x.
- for the time being, all distributions should ensure that `python` refers to the same target as `python2` .

**Comment by anishathalye** [comment]
Okay, guess we need a wrapper script.

There are enough systems with only Python 2 installed that I don't want to drop support for Python 2.

**Comment by vvug** [comment]
Take a look at this trick (needs to be adapted, but you get the idea):

http://stackoverflow.com/a/26056481

**Comment by anishathalye** [comment]
Cool, thanks for the pointer!

Here's a fix: https://github.com/anishathalye/dotbot/commit/dbf52c34ec245e1428f4739a30e44634be445039

It works for me. Let me know if it works for you, and then I can merge it.

**Comment by vvug** [comment]
Works for me too, thank you.

**Comment by paride** [comment]
I'd just change the order of the binaries, looking for `python3` first. But that's up to you.

**Comment by anishathalye** [comment]
Hmm, good point. Moved `python3` up to the top.

Commit 53eb3851d1115bc825bdf1c4d6f9407e8ff414d4 (v1.11.0) incorporates these fixes.

Thanks for the bug report!
