### ISSUE TITLE
Can't update dotbot

### ISSUE THREAD

**Issue by vvug** [anishathalye/dotbot#119]
This is probably a trivial problem, sorry for that. I can't update `dotbot` following the instructions in the README. The current situation is:

```
~$ cd ~/dotfiles/dotbot
~/dotfiles/dotbot$ git status
HEAD detached at ef558f8 # This is the point when I first installed dotbot.
```

Now, the documentation says:
> You can upgrade Dotbot at any point. If using a submodule, run `git submodule update --remote dotbot`

Indeed it seems to work:

```
~/dotfiles$ git submodule update --remote dotbot
Submodule path 'dotbot': checked out 'c29ba8d72224b545cbd7cf9446c3ed2ef13f8c24'
~/dotfiles$ cd dotbot
~/dotfiles/dotbot$ git show --summary
commit ef558f85d917c7d2fb52c17db10f0996ef92cb3f
Author: Anish Athalye <me@anishathalye.com>
Date:   Mon Mar 6 15:11:02 2017 -0500

    Update dates

```

That was actually the last commit. But when I run `./install` che old version is checked out:

```
:~/dotfiles$ ./install
Submodule path 'dotbot': checked out 'ef558f85d917c7d2fb52c17db10f0996ef92cb3f'
[...]

~/dotfiles$ cd dotbot
:~/dotfiles/dotbot$ git status
HEAD detached at ef558f8
```

The same happens if I upgrade with `git fetch && git checkout origin/master` (the other method suggested in the README).

What causes this is the `git submodule update --init --recursive "${DOTBOT_DIR}"` line in `dotbot/tools/git-submodule/install`. Am I missing something? How am I supposed to do a persistent upgrade?

**Comment by nagromc** [comment]
You need to commit the updated check-out version of `dotbot`.

```shell
$ git submodule update --remote dotbot
Submodule path 'dotbot': checked out 'c29ba8d72224b545cbd7cf9446c3ed2ef13f8c24'
$ # You can see here that the dotbot repo is dirty:
$ git status -s
## master...origin/master
 M dotbot
$ # In fact, the commit pointer to the dotbot repo has changed:
$ git diff
diff --git a/dotbot b/dotbot
index 28959a3..c29ba8d 160000
--- a/dotbot
+++ b/dotbot
@@ -1 +1 @@
-Subproject commit 28959a3f31d8632975de4e18d0a0e47476b5a413
+Subproject commit c29ba8d72224b545cbd7cf9446c3ed2ef13f8c24
$ git commit -a -m "Update dotbot"
$ # Everything should be fine from now on:
$ ./install
# blah blah
==> All tasks executed successfully
```

**Comment by vvug** [comment]
That was it indeed, thank you.
I would suggest adding the step to the documentation.

What about integrating these commands in the `install` script, so dotbot auto-updates every time it's run, or providing a `dotbot/tools/git-submodule/update` script that updates dotbot?

**Comment by nagromc** [comment]
It is a good idea to include this extra step into the documentation.

However, I think it is not a good idea to update Dotbot avery `install` is run. It should be up to the user.

But including an update script would make Dotbot easier to use for more users. I like the idea.

**Comment by vvug** [comment]
Agreed, updating should be up to the user.

**Comment by anishathalye** [comment]
I added a note to the readme in 096035dd98d14949fddd798822878e4b6c952e8c.

**Comment by vvug** [comment]
Thanks. Close this issue if you want, unless you prefer to keep it open to track the request for an `update` script.

**Comment by anishathalye** [comment]
Hmm, I don't really want an update script, because it's pretty easy to update using `git` directly. Plus, I think it would be weird to have the the update script make a Git commit on its own (and if it didn't, then the update would be reverted on the next `./install`).
