### ISSUE TITLE
Symlink all sub-directories

### ISSUE THREAD

**Issue by StFS** [anishathalye/dotbot#121]
Hi. I'm trying to figure out whether dotbot supports linking all sub-directories of a specified root directory into a destination directory rather than linking the root directory itself.

An example case is that I want to have a ohmyzsh-plugins directory in my dotbot where I add maybe 2 custom plugins. I want to link them into my ~/.oh-my-zsh/custom/plugins/ directory but a) that directory already exists and b) there may be directories there that I want to leave as is.

Do I have way of doing this other than specifying each and every subdirectory of ohmyzsh-plugins/ and manually linking them into ~/.oh-my-zsh/custom/plugins/ ?

**Comment by anishathalye** [comment]
Dotbot does not currently have such a feature. You need to either manually specify all the directories or link the root directory itself.

**Comment by anishathalye** [comment]
Does this come up often?

If anyone like to implement this as a feature (perhaps as a link option), that could be useful.

**Comment by hupfdule** [comment]
Hello I'd like to reopen that issue. I think this would be really useful. See especially the description of #16 which is actually the same request. The original author of #16 seems to be happy with fiddling with the `.gitignore` file, but actually I wouldn't consider this a solution, but more a workaround.

Such a feature would be really great if supported by dotbot directly.

**Comment by anishathalye** [comment]
I'd be fine including this as a feature. Perhaps a link option `subdirectories: true` (or something like that).

Is anyone interested in working on this and submitting a pull request? (if not, I'll get around to implementing it eventually)

**Comment by anishathalye** [comment]
I think this is solved by `glob:` merged in 2f4cc0d (v1.12.0).
