### ISSUE TITLE
Can you have symlinks to /etc files?

### ISSUE THREAD

**Issue by DavidAwad** [anishathalye/dotbot#124]
So I've been trying to use dotbot for links to `/etc/hosts` and it doesn't seem to work properly. Have you tried using dotbot to make links for files like `/etc/hosts` or `/etc/bash_profile`? 

Thanks!

**Comment by anishathalye** [comment]
Is it not working because you need to be root to write to /etc/hosts?

Try running Dotbot as root?

**Comment by nagromc** [comment]
@anishathalye is right. You need to run `sudo ./install` to grant `root` access to Dotbot.

I've managed to change some files in `/etc` using Dotbot. I just run `sudo ./install`.
See https://github.com/nagromc/machine-configuration/tree/samsung-ativ-book-9-plus-ubuntu

**Comment by DavidAwad** [comment]
That actually wasn't the problem, it looks like you just can't have symlinks to system files. using a hard link seems to solve the problem.
