### ISSUE TITLE
Unit test failure

### ISSUE THREAD

**Issue by nagromc** [anishathalye/dotbot#127]
When I run the unit tests by running `./test`, I have the following result:

```
test report
-----------
-  27 run
-   6 passed
-  21 failed

==> not ok!
(tests run in 1327 seconds)
```

Moreover, the 27 tests ran in 22+ minutes (!) on a Core i5-4200U @2.6GHz with 4 Gb.

Am I missing something?

**Comment by anishathalye** [comment]
Okay, so tests are super slow because we essentially run each test in a fresh VM: we checkpoint the VM between tests, and we restore from the snapshot before running every test. (The travis-ci integration doesn't do that, though)

This should probably be fixed at some point, but I'm not sure how to get a similar effect with another method that's faster. Having each test run on a "fresh machine" is pretty nice. Maybe we should think about replacing Vagrant with Docker and using #114.

As for the unit test failure -- I'm not sure why it's failing. The Travis CI build is working, and the tests work on my computer. Here's the output from `cd test && vagrant up && ./test`: https://gist.github.com/anishathalye/aef2ad7875e1ee2602064ada9c29294f

**Comment by dein0s** [comment]
Well, here are two reports after running tests in Docker env (worth to mention, that all actions were performed inside VM itself: windows host -> vm linux guest -> docker):
1. docker image not installed https://gist.github.com/dein0s/9604e6c5a3b7c006c3992271052cdd03
2. docker image already installed https://gist.github.com/dein0s/59c9c77c4f081c2603339c905988fb7a

**Comment by nagromc** [comment]
@dein0s Thanks for sharing your work. On a Core 2 Quad Q9550 @2.83 GHz with 4 Gb, the tests run in 40 minutes. Okay, that's an old CPU.

But I have the same results: 21 tests failed.

```
test report
-----------
-  27 run
-   6 passed
-  21 failed

==> not ok!
(tests run in 2420 seconds)
```

I will post soon the complete logs from my two machines.

**Comment by nagromc** [comment]
Is there a way to get the complete logs per `*.bash` instead of just the following?

```
initializing.
running 27 tests...

[1/27] (shell-disables-stdout.bash)
shell command stdout disabled by default
-> ok.

[2/27] (clean-missing.bash)
clean deletes links to missing files
- run failed.
-> fail!

...
```

**Comment by dein0s** [comment]
You can set [`DEBUG`](https://github.com/anishathalye/dotbot/blob/master/test/test-lib.bash#L1) to `true`.
Also you can turn on additional shell params (like [`set -x -v`](https://explainshell.com/explain?cmd=set+-v+-x)), but be prepeared for a huge wall of text :)

**Comment by nagromc** [comment]
OK thank you @dein0s

Here are the logs with `DEBUG` set to `true`:

```
initializing.
running 28 tests...

[1/28] (shell-disables-stdout.bash)
shell command stdout disabled by default
Traceback (most recent call last):
  File "/dotbot/bin/dotbot", line 39, in <module>
    import dotbot
  File "/dotbot/dotbot/__init__.py", line 1, in <module>
    from .cli import main
  File "/dotbot/dotbot/cli.py", line 4, in <module>
    from .config import ConfigReader, ReadingError
  File "/dotbot/dotbot/config.py", line 1, in <module>
    import yaml
ImportError: No module named yaml
-> ok.

[2/28] (clean-missing.bash)
clean deletes links to missing files
Traceback (most recent call last):
  File "/dotbot/bin/dotbot", line 39, in <module>
    import dotbot
  File "/dotbot/dotbot/__init__.py", line 1, in <module>
    from .cli import main
  File "/dotbot/dotbot/cli.py", line 4, in <module>
    from .config import ConfigReader, ReadingError
  File "/dotbot/dotbot/config.py", line 1, in <module>
    import yaml
ImportError: No module named yaml
- run failed.
-> fail!

...
```

The tests clearly state that the `yaml` module is missing, but the first test passes, while the second one fails. I'm lost :-)

**Comment by dein0s** [comment]
Well, some of them, which doesn't rely on data from config file, may pass: [shell-disables-stdout.bash](https://github.com/anishathalye/dotbot/blob/master/test/tests/shell-disables-stdout.bash) for example.

**Comment by nagromc** [comment]
OK I thought `git submodule update --init --recursive --remote` were run like any other Dotbot-powered dotfiles repo. Actually, Vagrant seems to [copy the local Dotbot installation](https://github.com/anishathalye/dotbot/blob/0b01d56d81c33f8b665487f5a64f2d69b2a645f0/test/Vagrantfile#L5) on the VM. So I need to run `git submodule update --init --recursive --remote` on my own Dotbot engine repo, right?

Regarding my [previous comment](https://github.com/anishathalye/dotbot/issues/127#issuecomment-307651390), OK I have now some kind of stack traces. But, since I have the same trace for passed and failed tests, I guess I need to enable `set -x -v` you told me about. Am I supposed to add those switches in my `test/test-lib.bash` file (like for `DEBUG`)?

**Comment by dein0s** [comment]
> So I need to run git submodule update --init --recursive --remote on my own Dotbot engine repo, right?

Yes, you're right.

> Regarding my previous comment, OK I have now some kind of stack traces. But, since I have the same trace for passed and failed tests, I guess I need to enable set -x -v you told me about. Am I supposed to add those switches in my test/test-lib.bash file (like for DEBUG)?

There's no need to run tests untill you fix previous problem with submodule as nothing will change I guess and everything will fail on parsing configs.

**Comment by nagromc** [comment]
OK that's much better now :+1: I will add that to #126.
