### ISSUE TITLE
Add suppressShellCmd config option

### ISSUE THREAD

**Issue by thtliife** [anishathalye/dotbot#131]
This issue is to track changes for a pull request adding the feature.
Add the ability to suppress the actual command output.
Essentially to enable output in the shell section to be either the current format:
```
  Creating downloads directory [mkdir -p ~/downloads]
```

or if setting suppressShellCmd to true in either the item or defaults, to display only the message (if it exists)
```
  Creating downloads directory
```

**Comment by anishathalye** [comment]
Merged #132.
