### ISSUE TITLE
Possible to install prezto?

### ISSUE THREAD

**Issue by breerly** [anishathalye/dotbot#14]
How would I get prezto going with dotbot? Not possible?

**Comment by anishathalye** [comment]
Yeah, it's possible. For example, you can do what mmailhot or maschs did as a reference: https://github.com/mmailhot/dotfiles / https://github.com/maschs/dotfiles

You can add prezto as a submodule, link the folder using Dotbot, and add the appropriate stuff to your .zshrc files.

**Comment by breerly** [comment]
This repo appeared to setup it up right, with a submodule and prezto configs in the dotfiles repo:

https://github.com/ejel/dotfiles

**Comment by anishathalye** [comment]
Thanks for following up! I'm sure other people will find this useful.
