### ISSUE TITLE
[Feature] Link all in folder

### ISSUE THREAD

**Issue by robobenklein** [anishathalye/dotbot#141]
We can link folders with simple syntax like
```yaml
- link:
    ~/.config:
```
But let's say I wanted to link everything in `./config/*` into `~/.config/` so that it would link all the folders in `~/.config` that are in the repo already, but the million other things in `~/.config` don't show up back in the git repo.

Perhaps a new syntax style purpose for trailing slashes:
```yaml
- link:
    ~/.config/: config/*
```
Would link all the files/folders in `./config/` to their places in `~/.config/`

This would make it extremely easy to automatically link a lot of configs in the repo with just one entry in the YAML.

Taking this idea further we could get:
```yaml
- link:
    ~: home
```
Which would take all the files/folders in `./home/*` or the repo and link them each into `~/`. (`./home/` could have things like `.tmux.conf` and `.bashrc` in it which would all be linked to `~/`.)

I had this idea as I was trying to do something similar using an `ln` command like `ln -ns $(pwd)/config/* $HOME/.config/` however this command nonzero exits when any of the files exist, or with `-f` I didn't want it to overwrite without making any backup.

**Comment by anishathalye** [comment]
Seems like a neat idea; would be happy to implement this / accept a PR as long as there are no backwards compatibility issues.

Are there any issues with `*`? Technically, it's legal to have it in a file name.

Also, with the second syntax you proposed:

```yaml
- link:
   ~: home
```

How would you distinguish between wanting to symlink a directory vs wanting to individually symlink the files within it?

**Comment by arcticicestudio** [comment]
One idea to solve these edge cases (files named `*`, folders/files named `home`) would be to add a CLI option e.g. `--enable-globs` which must be implicitly added by the user, otherwise dotbot should handle them like "normal" files/folders.

Another way might be to add a boolean flag (default to `False`) to the `link` plugin (e.g. `use_globs`) to enable name globbing individually for each entry.

**Comment by robobenklein** [comment]
Yeah I missed trailing slashes on my home example.

I like your idea of the `use_globs` flag, being explicit is always good, I'll see what I can do to implement that.

**Comment by anishathalye** [comment]
The `use_globs` sounds like a good idea, we can implement in the same way like `create` and `relink` and `force`.

Still doesn't solve the problem when you don't have the trailing `*` though. Like if you're interpreting this `~: home` or even `~: home/`, currently, Dotbot will do the equivalent of symlinking `~` to point to the `home` folder in the current directory.

**Comment by robobenklein** [comment]
It was supposed to have the trailing slash at the end of `~/`:
```yaml
link:
    ~/: home/*
```

**Comment by anishathalye** [comment]
ah, yes, the `/*` notation should be fine (people probably don't have files named `*` :P)

**Comment by anishathalye** [comment]
#142 has been merged 🎉
