### ISSUE TITLE
[Feature] Linking where sudo is needed

### ISSUE THREAD

**Issue by ddnomad** [anishathalye/dotbot#144]
It would be great to have an option to link `udev` rules or similar configuration though it requires super user rights. 

The question is more of "what is the best way to implement it" right now. Is it should be a separate plugin or is it better to add straight to `link` plugin. 

My thought is that implementing a separate plugin would be an overkill as it would duplicate most of `link` plugin functionality adding only some safety measures and `su` prompt at the end of a day. 

What do you think?

**Comment by arcticicestudio** [comment]
There's already a discussion about it in #125.

**Comment by ddnomad** [comment]
Oh, my apologies for being too lazy to search for issues first.

The issue with `os.symlink` and `sudo` is a nasty one though.

-------- Original Message --------

**Comment by anishathalye** [comment]
I see you've commented in #125. I'm going to close this duplicate issue and reply in #125.
