### ISSUE TITLE
Fails to symlink Sublime Text config

### ISSUE THREAD

**Issue by nikitavoloboev** [anishathalye/dotbot#145]
[This](https://github.com/nikitavoloboev/dotfiles/blob/master/.install.conf.yaml) is my dotbot config YAML.

On line 24 there I try to symlink Sublime Text:
`~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User: sublime`

The path is correct. However it fails on me when I run my [install script](https://github.com/nikitavoloboev/dotfiles/blob/master/install).

```Bash
~/.dotfiles master
❯ ./install
Link /Users/nikivi/.bash_profile -> /Users/nikivi/Dropbox/Mackup/.bash_profile not removed.
Link /Users/nikivi/.gitmodules -> /Users/nikivi/dotfiles/zprezto/.gitmodules not removed.
All targets have been cleaned
Installing submodules [git submodule update --init --recursive]
All commands have been executed
Link exists ~/.zshrc -> /Users/nikivi/.dotfiles/zsh/zshrc.zsh
Link exists ~/.gitconfig -> /Users/nikivi/.dotfiles/git/gitconfig
Link exists ~/.gitignore_global -> /Users/nikivi/.dotfiles/git/gitignore_global
Link exists ~/.hammerspoon -> /Users/nikivi/.dotfiles/hammerspoon
Link exists ~/.ideavimrc -> /Users/nikivi/.dotfiles/idea/ideavimrc
Link exists ~/Library/Application\ Support/Karabiner -> /Users/nikivi/.dotfiles/karabiner
Nonexistent target ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User -> sublime
Link exists ~/.config/nvim -> /Users/nikivi/.dotfiles/nvim
Link exists ~/Library/Application\ Support/Code/User -> /Users/nikivi/.dotfiles/vscode
Link exists ~/.tmux.conf -> /Users/nikivi/.dotfiles/tmux/tmux.conf
Some links were not successfully set up

==> Some tasks were not executed successfully

```

I am really not sure why that goes wrong. Shouldn't it work?

Thank you for any help.

**Comment by anishathalye** [comment]
Looking at the output:

```
Nonexistent target ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User -> sublime
```

This says that the target `sublime` doesn't exist.

**Comment by nikitavoloboev** [comment]
I thought that this:

```Bash
- defaults:
    link:
      create: true
      relink: true
```

Specifically this `create: true` line would create a folder if it doesn't exist.

**Comment by anishathalye** [comment]
It creates the folder; the problem is that the symlink _target_ is missing. Is there a file called `sublime` in your dotfiles directory?

**Comment by nikitavoloboev** [comment]
There isn't. Perhaps I misunderstand it. But I thought that this line: 

`~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User: sublime`

Will symlink contents of `~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User` inside directory `sublime`.

**Comment by nikitavoloboev** [comment]
Another issue I have, perhaps related. I want to symlink `.zshrc` inside `zsh` directory with custom name.

So I added this line:
`~/.zshrc: zsh/zshrc.zsh`

This fails saying that `Nonexistent target ~/.zshrc -> zsh/zshrc.zsh`.

But the file is there:

![2018-02-04 at 03 29](https://user-images.githubusercontent.com/6391776/35773772-102e06e4-095c-11e8-8029-c01c9a163069.png)

**Comment by nikitavoloboev** [comment]
I guess I understand now what you mean by `target`. So I have to create the file/folder beforehand?

Can't dotbot create the files/folders from the YAML config? I just specific what I want to symlink and to where.

**Comment by anishathalye** [comment]
Ah, I think you're getting the left and right hand sides mixed.

Suppose you have a file `zsh/.zshrc` in your dotfiles directory, e.g. `/home/nikita/src/dotfiles/zsh/.zshrc`. Then you'd want to include the line `~/.zshrc: zsh/.zshrc` in your `/home/nikita/src/dotfiles/.install.conf.yaml`.

**Comment by anishathalye** [comment]
Using the standard workflow, you have files inside your revision-controlled dotfiles directory, and you create symlinks from outside locations (e.g. your home folder), so you might have `~/.zshrc` point to a file `zsh/.zshrc` in your Dotfiles.

**Comment by nikitavoloboev** [comment]
But what if the original file is in ~/.zshrc and I want to symlink it to ~/.dotfiles/zsh/zshrc.zsh?

**Comment by nikitavoloboev** [comment]
Would that work out to be?
`~/.dotfiles/zsh/zshrc: ~/.zshrc`

Looks odd and not like any other dotbot config I saw.

**Comment by anishathalye** [comment]
Why would you want `~/.dotfiles/zsh/zshrc.zsh` to be a symlink? Then the only thing you'd have in version control is that you have a symlink (you won't have the contents).

**Comment by nikitavoloboev** [comment]
I want the original file to be in ~/.dotfiles/zsh/zshrc

But you have to move it there first, no? What I do now which is really painful is that if I want to move some config under my dotfiles.

I first, move the original file to my dotfiles. Then create a symlink to that file from the place I moved it.

**Comment by nikitavoloboev** [comment]
So dotbot can't do the moving part as well?

**Comment by anishathalye** [comment]
Nope, not currently. The idea was to automate the tasks that you do again and again (symlinking, as you sync your dotfiles between your computers), but it doesn't currently automatically move the file from outside into your git directory.

**Comment by nikitavoloboev** [comment]
Yeah that makes sense. Thank you @anishathalye

**Comment by nikitavoloboev** [comment]
Just curious. Say I do this on a new machine. Would dotbot swap the original file and create a symlink of it? Like is the case of `.zshrc` which will certainly be present.

**Comment by anishathalye** [comment]
Not with your current config, but if you switch `relink: true` with `force: true`, then yes.
