### ISSUE TITLE
Activate zsh by default.

### ISSUE THREAD

**Issue by breerly** [anishathalye/dotbot#15]
dotbot works great, except for that zsh isnt activated until I actually type `zsh`. Is there a way to get that to automatically be the default shell with dotbot?

(sorry if this is a silly question)

**Comment by anishathalye** [comment]
That's probably not something that you should be using Dotbot to be using -- it's a system setting.

You can use chsh(1) to change your default shell. You can find the path to zsh using `which zsh`. Then you can run (with the correct path):

`chsh -s /usr/bin/zsh`

You may need to enter your password when prompted.
