### ISSUE TITLE
Make clean align with link globbing

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/dotbot#151]
See discussion in #142 / #149

It would be nice to align the behavior of clean with that of link (now with globbing support). Maybe this can be done by supporting globs in clean. Would we also want an option to remove empty directories? Would we want clean to be recursive?

CC @dsifford @robobenklein

**Comment by Kidlike** [comment]
Hi, fresh user of dotbot here.

My personal preference is that `dead links` are ok to be removed. BUT, I don't think it should be the default. By default nothing should be removed that is not explicit. e.g. someone may have binaries on a removable device (or encrypted & mountable volume) that are soft linked to ~/bin.

Same goes for `empty directories`. By default not remove anything not explicit. e.g. mount folder (empty if not mounted).

I would say that 2 separate options for the above would be ideal.

**Comment by anishathalye** [comment]
So by default, no links are removed. If the config file includes `clean`, then the listed directories are cleaned for dead links, but only the links that point within the dotfiles base directory are removed, unless the user has also specified `force`.

Rather than add globbing support to clean, I think it makes more sense to add a `recursive` flag (e38e021ab324ea676a285ac4667f1fba1469a6bf). E.g. I think I will have Dotbot clean `~`, and clean `~/.config` recursively.
