### ISSUE TITLE
Option to avoid symlink target checking

### ISSUE THREAD

**Issue by apuignav** [anishathalye/dotbot#153]
As part of my install process, I point a few links to my Dropbox folder, which has typically not been installed yet when I install a new machine. I would like to be able to keep the links pointing to non-existent locations so that they are there when I install dropbox.

Currently, I get a "non-existent" warning, which stops the running of the Dotbot script. Would it be possible to add a `ignore-missing` flag so that this sort of use-case can be supported? Or maybe I haven't found the correct way to do it?

**Comment by robobenklein** [comment]
I think this should be easy enough to implement. Once we get the LinkIf and PyYAML done, I'll be glad to make another PR for it. Shouldn't be too hard, considering it's just *reducing* the amount of work dotbot does as a boolean expression.

**Comment by apuignav** [comment]
I have tried a first implementation (in the linked commit), should I open a MR?

**Comment by anishathalye** [comment]
Sure, please open a PR @apuignav

**Comment by anishathalye** [comment]
Fixed in #178, now merged.
