### ISSUE TITLE
Add a way to only run the `link:` section

### ISSUE THREAD

**Issue by nikitavoloboev** [anishathalye/dotbot#164]
I have [dotbot config](https://github.com/nikitavoloboev/dotfiles/blob/master/.install.conf.yaml) that will soon have quite a few commands I want to run to install programmes. Basically using the script as a way to install all the necessary things to a fresh mac.

I don't want those to be ran every time I run `./install` however and sometimes I just want to symlink things.

Is it possible to pass something to `./install` to only run the symlinks?

**Comment by anishathalye** [comment]
See #44 -- it's a proposed feature, but we haven't implemented it yet.
