### ISSUE TITLE
Fix PyPI package to bundle executable with python3.7

### ISSUE THREAD

**Issue by dsifford** [anishathalye/dotbot#167]
For whatever reason, installing this with python3.7 doesn't link the binary in ~/.local/bin like other python versions do. I'm assuming this has something to do with setup.py.

Side note: Have you considered using Poetry to bundle and ship this rather than setuptools? It seems like it would be way easier to use/maintain.

**Comment by anishathalye** [comment]
Hmm, there isn't really python version specific code in `setup.py`. Is this an issue with Python 3.7?

setuptools seems pretty standard. Are there any big projects switching to Poetry?

**Comment by dsifford** [comment]
Not sure for both of your questions. Haven't really used poetry myself for anything of substance, but it ostensibly appears to do most of the heavy lifting automatically using just a pyproject.toml

**Comment by dsifford** [comment]
Disregard... Apparently my understanding of how pip works internally was what was flawed.

Apparently if dotbot is installed with pip3.6 and the binary is linked to `~/.local/bin`, then subsequently installing dotbot using pip3.7 will skip linking the binary upon installation.

The "fix" was to just uninstall for python3.6 and reinstall for python3.7.

**Comment by anishathalye** [comment]
Whew, I thought this was yet another issue with our setup.py / pypi setup 😛 

Glad it's working for you now.
