### ISSUE TITLE
Shell - Some commands were not successfully executed

### ISSUE THREAD

**Issue by shivapoudel** [anishathalye/dotbot#170]
I am receiving Some commands were not successfully executed message with this below config :) 
![capture](https://user-images.githubusercontent.com/3774827/46244483-1a4b0100-c3ff-11e8-9bd3-d8662fa48650.PNG)

This is my `install.conf.yaml` file. I am on Windows 10 with Dotbot 1.12.5:
```
- defaults:
    link:
      force: true
      create: true
      relink: true

- clean: ['~']

- link:
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
    ~/.minttyrc: mintty/minttyrc
    ~/.npmrc: npm/npmrc
    ~/.vim: vim/vim
    ~/.vimrc: vim/vimrc

- shell:
  - vim +PluginInstall +qall
```

**Comment by anishathalye** [comment]
Looks like your `vim +PluginInstall +qall` failed. Some steps I'd take when debugging:

- try running it directly in your terminal to see if it returns successfully
- run it with `stdout: true` / `stderr: true` in Dotbot and see if it prints any errors

**Comment by shivapoudel** [comment]
Modify config shell setup to like this:
```
- shell:
    -
      command: vim +PluginInstall +qall
      stdout: true
```
No luck @anishathalye same error and I don't get any output too

**Comment by anishathalye** [comment]
Did you try running it directly? Also, did you try enabling stderr too?

**Comment by shivapoudel** [comment]
@anishathalye I am using Mintty which is shipped in Git for Windows. Tried stderr too but no luck :)

**Comment by anishathalye** [comment]
What happens if you run the command directly?

**Comment by shivapoudel** [comment]
It work with direct execution :)

![capture](https://user-images.githubusercontent.com/3774827/46261313-a6e5e400-c511-11e8-9d59-d11cefc3ca40.PNG)
![capture-1](https://user-images.githubusercontent.com/3774827/46261314-a6e5e400-c511-11e8-9a54-5ec3a3735843.PNG)

**Comment by anishathalye** [comment]
I don't use vim plug, so I'm not very familiar with it. Does it require input on stdin before proceeding? Also, this issue seems somewhat related: https://github.com/junegunn/vim-plug/issues/225

**Comment by shivapoudel** [comment]
@anishathalye solve through running Git CMD with administritive privilage instead of Git Bash.

**Comment by anishathalye** [comment]
Nice, glad you got it working!
