### ISSUE TITLE
Linking dotfiles to another location

### ISSUE THREAD

**Issue by Brottweiler** [anishathalye/dotbot#172]
I understand that from the config usually you link to ~, and you can change this to another folder outside of home even.

I am setting up my dotfiles on a new drive (I'm replacing it), so while the new drive will be home later, right now it will be mounted somewhere else.

I am going to clone the dotfiles to that new drive, but if I run the script it will link to home.

How would I be able to link to the mounted drive? Would `HOME=/mnt/home ./install` be enough so the command thinks the mounted drive is the home?

**Comment by anishathalye** [comment]
Yes, that should work.

Dotbot expands paths using `os.path.expanduser()`. From the documentation for that library function:

> On Unix, an initial ~ is replaced by the environment variable HOME if it is set; otherwise the current user’s home directory is looked up in the password directory through the built-in module pwd.

**Comment by Brottweiler** [comment]
Cool! It worked, thanks!

It's weird, I tried to just do something like `HOME=/mnt/new_home/brott touch ~/test_file` and even `HOME=/mnt/new_home/brott echo $HOME`, but it made the file in my normal home and returned `/home/brott`.

But surprisingly, it worked fine with dotbot!

**Comment by anishathalye** [comment]
Your shell expands $HOME based on its environment variables; if you do, e.g. `HOME=/mnt/new_home/brott $SHELL` and then run those commands in the shell you just launched, it'll work as you expect.

**Comment by Brottweiler** [comment]
I seem to have made a mistake. When creating the links, I did so when my new drive was mounted in a differnet location. So now all the links point to `/mnt`, when they should point to `~`. I probably need to manually remove them all, then re run the script

**Comment by Brottweiler** [comment]
After all, I ended up removing all the links manually. Then I started my computer with the new home drive, ran the script. Then rebooted so make sure everything was in order
