### ISSUE TITLE
Simplify README by removing JSON examples

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/dotbot#174]
Dotbot will retain JSON support (it's a subset of YAML anyways). But perhaps it's worth removing the JSON examples from the README, because it adds a lot of clutter to duplicate everything.

A counterargument is that sometimes JSON is clearer than YAML because of all the implicit stuff in YAML (e.g. `true` becomes the boolean true and needs to be put in quotes if you want the string `"true"`).

Would love to hear others' thoughts on this.

**Comment by anishathalye** [comment]
Might be worth doing a quick user study to see what percent of people are using YAML vs JSON. 

@casey has done this already: https://github.com/casey/dotbot-user-study, though the results are ~ 3 years old. As of that time, it seemed to be ~ 7% JSON, ~ 93% YAML.

(might also be neat to see what else we can learn from the user study)

**Comment by casey** [comment]
Oh man, I forgot I did this. I tried to re-run it to pull new configs, but it looks like the code has rotted a bit. I don't have time to tackle it at the moment, but it's probably an easy fix.

**Comment by anishathalye** [comment]
Done in b062aeaf15f1b174f6c9b88a0b2017b06d7fbd3e.
