### ISSUE TITLE
Request update pyyaml submodule

### ISSUE THREAD

**Issue by septs** [anishathalye/dotbot#176]
![image](https://user-images.githubusercontent.com/3842474/51810078-9f2c2580-22e0-11e9-8138-cd46a3f9189f.png)

pyyaml library added `.gitignore` file

see https://github.com/yaml/pyyaml/blob/a27099bb68d5f045999d61f04476114292ce6ea5/.gitignore#L9-L10

**Comment by anishathalye** [comment]
I don't understand exactly what you are suggesting - could you clarify?

**Comment by septs** [comment]
pyyaml introduced version before without `.gitignore` so it will generate `.pyc` file at runtime
Now `pyyaml` introduces `.gitignore` so you can hide these changes

I can see these files when using vscode maintenance.

**Comment by anishathalye** [comment]
The current PyYAML version that Dotbot uses seems to work fine, I don't think there's any reason to upgrade the dependency.

Plus, there seem to be issues with more recent releases, e.g. see the comments in https://github.com/hydrosquall/tiingo-python/pull/124. The 4.1 release has been pulled (I think for bugs with Python 3.7 compatibility?), and there is no 4.2 release yet.

Also, you should be able to configure your editor to ignore pyc files (which should probably be ignored in a global gitignore anyways).
