### ISSUE TITLE
run a script on the shell with sudo

### ISSUE THREAD

**Issue by magicalbanana** [anishathalye/dotbot#18]
So how do I go on about calling a script on the yaml file with sudo?

Let's say I have a directory and on the root is a directory called scripts, how do I run a script in that directory and prompt for sudo when needed or as an entire execution?

**Comment by anishathalye** [comment]
I'm not 100% sure what exactly you're asking, so correct me if I'm wrong.

It sounds like you want to run some interactive bash scripts (or similar) that are located a subdirectory of your dotfiles folder, and you want to be able to use `sudo` in the scripts and have it prompt you for a password. You can do that using a `shell` command in your `install.conf.yaml` using the extended syntax to be able to use the additional options.

Commands are executed in your dotfiles directory, so you can specify relative paths and it'll work out just fine. You can also enable stdin/stdout/stderr as required.

For example, suppose you had a bash script in your dotfiles directory, in `scripts/test` (and the execute bit was set, or you called `bash scripts/test` explicitly):

```bash
#!/usr/bin/env bash
sudo echo this is being run as root for no good reason
```

Then you could have your `install.conf.yaml` as follows:

```yaml
- shell:
  -
    description: "Run test script"
    command: "./scripts/test"
    stdout: true
    stderr: true
    stdin: true
```

This should work like you want it to. You can disable stdin/stdout/stderr as desired (and if you omit the line, it defaults to disabled).

**Comment by magicalbanana** [comment]
Thanks @anishathalye. Reason is, I have both OSX and Linux based distros and I often am spinning fresh dev environments (that includes installing rails, spring, etc). So I wanted to create a one dotfile installer for all but currently the only way I can differentiate between OSX and Linux is $(uname -s).

But this is awesome, will try it out. Once I am done, perhaps I can add this to a template thing for those who want a fresh dev environment for rails or node development. :dancers:

**Comment by anishathalye** [comment]
Ok, I see, that makes sense.

You may also be interested in doing something like what was discussed in #11, perhaps even adding platform detection by `uname -s` to select which `install.conf.yaml` file you use.

Also, you could take the approach I use -- I have [dotfiles](https://github.com/anishathalye/dotfiles) contain all the shared stuff, and then I have per-machine configuration in [dotfiles-local](https://github.com/anishathalye/dotfiles-local), where there is one branch corresponding to a machine or set of machines (currently with 6 sets of configuration).
