### ISSUE TITLE
Regex/format string syntax for link targets?

### ISSUE THREAD

**Issue by OxSon** [anishathalye/dotbot#183]
Hi.

In my dotfiles, I have a large number of files that need to live in the home folder, all of which have names which are of the form .`<something>`. For organizational purposes, I would like to have all such files in a sub folder of my dotfiles repo, called `home`, and have them stripped of the leading `.` character. Like this:
```
dotfiles
|--other stuff
|
|--home
   |--vimrc
   |--zshrc
   |--etc
```

I want to be able to write a rule in my `install.conf.yaml` that takes anything located in the `dotfiles/home` directory and links it to `"$HOME/."` + `<file-name>`.

I hope that explanation made sense. I tried to find a way to do this and was unsuccessful. Please let me know if this is currently possible and I have missed it. Love this tool! Thanks.

**Comment by anishathalye** [comment]
Hmm, I'm not sure if this is possible. Does the [glob](https://github.com/anishathalye/dotbot#format) functionality solve the problem?

Do you have so many files that you cannot list them all in the `.install.conf.yaml`?

**Comment by OxSon** [comment]
If I understand the glob functionality correctly, it would work if I had all the files under `home` named the same as I want them to be in my actual home folder, i.e. with a `.` prefix. It doesn't seem that I can make a rule that expresses "take any file, `file`, found in `folderA`, and link it to `$HOME/.file`. 

I have maybe 12 or so files that would fall under the scope of this rule if it were possible. Not so many that I can't do it manually, but enough to make me wish it were possible.

**Comment by anishathalye** [comment]
Ah yes, the glob doesn't do the removal of the `.`.

Listing 12 files doesn't seem too bad 😛 

#182 seems like a related (and perhaps strictly more general) feature. I haven't had a chance to think deeply about whether to implement the sed mechanism yet, but I think if we were to add support for your use case, we'd want to do it via something like #182.

**Comment by OxSon** [comment]
Yes after skimming [#182](https://github.com/anishathalye/dotbot/issues/182) that makes sense to me. I'll read it closer later on and think about how I might be able to help.

**Comment by anishathalye** [comment]
Similar to #182, I think this might be a rare enough case that it's not worth adding the complexity to Dotbot.
