### ISSUE TITLE
Keep color output when using as alias

### ISSUE THREAD

**Issue by daybugging** [anishathalye/dotbot#186]
Hey there,
first off: great software!

Now, I realise this might be more a bash-related question, but .. I want to keep the colorful output when using an alias like so:

```shell
alias dotbot="bash ~/.dotfiles/install.sh -c ~/.dotfiles/config.yml"
```

All I get is this gray goo:

![image](https://user-images.githubusercontent.com/23332902/59852210-ad9ddb00-936e-11e9-9f08-9c44b90988c7.png)

**Comment by anishathalye** [comment]
Hmm, I still see two colors (e.g. the first line "All targets..." looks different from the "Link exists" line).

Could this have something to do with your bash / terminal emulator color settings?

**Comment by anishathalye** [comment]
I'm guessing that this has been resolved? If not, feel free to reopen.
