### ISSUE TITLE
[Bug] Don't find python library from WindowsApps dir

### ISSUE THREAD

**Issue by shivapoudel** [anishathalye/dotbot#187]
I accidentally installed the Python library from Windows App which was the culprit for me. I am receiving this error message:

```
/c/Users/shivapoudel/.dotfiles/meta/dotbot/bin/dotbot: line 10: /c/Users/shivapoudel/AppData/Local/Microsoft/WindowsApps/python3: Permission denied
/c/Users/shivapoudel/.dotfiles/meta/dotbot/bin/dotbot: line 10: /c/Users/shivapoudel/AppData/Local/Microsoft/WindowsApps/python3: Permission denied
```

Later, I debug and found https://github.com/anishathalye/dotbot/blob/master/bin/dotbot#L10-L12 check is locating me there. Can this check be modified so that `which python3` is located from other place rather than `C:\Users\shivapoudel\AppData\Local\Microsoft\WindowsApps`

**Comment by anishathalye** [comment]
I don't fully understand why you're getting this issue. This means that `which python3` is showing that you have a `python3` installed, but for some reason, you can't execute it? Why does that happen?

[PEP 394](https://www.python.org/dev/peps/pep-0394/) and [PEP 397](https://www.python.org/dev/peps/pep-0397/) seem related to this issue.

**Comment by shivapoudel** [comment]
@anishathalye It is happening because the Windows App store Python app is always being installed and this is a global issue for Windows user. There is no way to opt-out using Windows App store application, just you can uninstall but 0 kb `python3` is still being loaded always.

**Comment by shivapoudel** [comment]
If we just check python3 at last then the problem will vanish because `python` can execute the task successfully. Its been a couple of months that I am facing this issue.

**Comment by anishathalye** [comment]
Why isn't the Windows app store `python` not executable?

**Comment by shivapoudel** [comment]
@anishathalye I had installed Python from the app store but later found [Microsoft Store python package](https://docs.python.org/3.7/using/windows.html#the-microsoft-store-package) is currently considered unstable. Thus I have installed the python from its main site. The problem is with App Store because I can uninstall the python but some binary files for python are never been deleted. If I delete once, they will re-appeared after a few moments. Thus while setting up dotbot, I have to always delete below screenshot python files and process further, which is being the hassle for me.
![image](https://user-images.githubusercontent.com/3774827/60143477-12798b00-97de-11e9-8ddd-742da76f2f87.png)

**Comment by anishathalye** [comment]
Hmm, so this seems like a problem with your system configuration rather than in Dotbot itself?

Since we aim to be compatible with both Python 2 and Python 3, it seems fine to try `python` before trying `python2` or `python3` specifically. This way, we'll be using the user's preferred `python` version. I think we still want to prefer Python 3 over Python 2, however. This is done in 9a8d292681ac540894dce3fe998be0068dfa2df5.
