### ISSUE TITLE
be clear about dotbot requirements

### ISSUE THREAD

**Issue by lliseil** [anishathalye/dotbot#19]
It'd be nice if yaml version (and any other requirements) were given with precision. As there are alredy various things to think about (did i say mess ;) for dotfiles, git or dotbot's starters who read that [dotbot has no external dependencies, so there is no extra work required when setting up new systems.][1] ;)

    $ cd ~/.dotfiles
    $ git clone <dotbot>
    $ vim {.gitignore,.gitmodules,.install.conf.yaml}
    $ mv ~/<.dotfile> <dotfile>
    $ cp .dotbot/tools/submodules/install .install
    $ ./.install
    Traceback (most recent call last):
      File "~/.dots/.dotbot/bin/dotbot", line 23, in <module>
        import dotbot
      File "~/.dots/.dotbot/dotbot/__init__.py", line 1, in <module>
        from .cli import main
      File "~/.dots/.dotbot/dotbot/cli.py", line 2, in <module>
        from .config import ConfigReader, ReadingError
      File "~/.dots/.dotbot/dotbot/config.py", line 1, in <module>
      1 # dotbot configuration (yaml)                                                    
        import yaml
    ImportError: No module named 'yaml'

Ooh sh*t!

    $ pacman -Qs yaml
    libyaml 0.1.6-1
    python2-yaml 3.11-1

Just like this [guy](http://answers.ros.org/question/11557/importerror-no-module-named-yaml/)

dotbot `./install` did well after I installed `python-yaml-3.11-1` :)

[1]: http://www.anishathalye.com/2014/08/03/managing-your-dotfiles/#installation

**Comment by anishathalye** [comment]
So Dotbot *doesn't* have external dependencies -- it's self contained, with the yaml component being separated out as a submodule, so you don't need to install the yaml library. It'll even automatically select the right version depending on which version of Python you're running.

If you use Dotbot via the standard method of git submodules, the `./install` script will automatically fetch Dotbot (and recursively download its submodules) by running `git submodule update --init --recursive "${DOTBOT_DIR}"`.

I highly recommend having Dotbot as a submodule in your dotfiles.

However, if you do want to just clone it, you can `git clone --recursive https://github.com/anishathalye/dotfiles`, and this will fetch the submodules. Also, you can fetch the submodules in an already-downloaded clone by going to the directory and running `git submodule update --init --recursive`.

**Comment by anishathalye** [comment]
I'm going to assume that this is resolved -- feel free to reopen it if there's anything else.

Also, if you have any suggestions on how to improve the documentation to make this clearer, I'd be happy to hear them.

**Comment by lliseil** [comment]
Thanks anishathalye. `Command [git update-submodules] failed` I somehow misdone "having Dotbot as a submodule". Will look at your dotfiles after I get this, and try again.

**Comment by wongjiahau** [comment]
I have to run `apt-get install python-yaml` in order to get it working.
