### ISSUE TITLE
Using dotbot for management config system-wide.

### ISSUE THREAD

**Issue by hongyi-zhao** [anishathalye/dotbot#195]
Hi,

I want to also use dotbot to management config system-wide instead of only  the dotfiles.

Say, for customized or revised stuff under /etc.

How to achieve this purpose?

**Comment by anishathalye** [comment]
I think there are some people who use Dotbot for this purpose, but I don't know if it's the right tool for that job. I think there's software like Salt/Puppet/Ansible that may be more suited for this purpose.

**Comment by hongyi-zhao** [comment]
I noticed the following:

https://www.anishathalye.com/2014/08/03/managing-your-dotfiles/

```
There are two main approaches for using a VCS to keep track of configuration files: you can have your entire home directory under version control (and ignore non-configuration files), or you can keep your configuration files in a separate directory and copy or link them into place. The latter approach is vastly superior for several reasons:

[...]
    It is possible to track configuration files that belong somewhere other than $HOME.
 [...]
```

**Comment by hongyi-zhao** [comment]
It seems the tools like Salt/Puppet/Ansible and so on, are too heavy for this type of job.

**Comment by anishathalye** [comment]
Oh sure, you can use Dotbot to symlink files to other locations (e.g. in `/etc`).

**Comment by hongyi-zhao** [comment]
As we all know, there are differences between dotfiles and other system-wide configs:

1. the dotfiles maybe created from scratch.
2. the other system-wide configs maybe or may not: 
a. if it already exists and we want to do some revision on it.
b. if it doesn't exist, this case is same as to dotfiles.

So, how to deal to these cases?

**Comment by hongyi-zhao** [comment]
If so, the dotfiles dirname will be incorrect.  Maybe named as configfiles which is just as I'm using.

**Comment by hongyi-zhao** [comment]
And the directory of configfiles should be as follows:

configfiles
        etc/
        home/werner/

And the link path rule used for now may be need for some revision.

Regards

ps.  I've forked your repo, and do some revisions based on my own understand/requirement.

**Comment by anishathalye** [comment]
Yes, so Dotbot is not designed to patch files, only to replace them entirely. This makes sense for dotfiles, but maybe makes less sense for files in `/etc`, depending on your setup.

Feel free to fork Dotbot to modify it to your use case 😄

**Comment by NathanielHill** [comment]
@hongyi-zhao I've switched from using dotbot for 4 years (thanks @anishathalye !) to using the simple bare repo method. It's incredibly simple, and doesn't involve symlinks or submodules :sweat_smile: 

https://www.atlassian.com/git/tutorials/dotfiles

You could also use this method to manage system configuration by using `/` or `/etc` as the working directory. You could have two aliases, one for user dotfiles and another for system config.

**Comment by anishathalye** [comment]
A small note on having your `$HOME` be directly under version control as the git work tree -- one danger is that a `git clean` (or similar command) could wipe out untracked files. This is the main reason I use symlinks.

**Comment by NathanielHill** [comment]
@anishathalye good point.

One could use a shell function instead of an alias and filter out any dangerous git commands if paranoid.

**Comment by dagadbm** [comment]
i actually tried using a bare repo solution before but it didnt gave me enough liberty ijn terms of folder structure and so on. so after searching the entire internets for dotfile management systems and so on i settled for dotbot which i believe is one of the best ones out there
i use a ton of sub modules but my handy modified install script just updates them all automagically for me.

feel free to check out my dotfiles if you are curious

**Comment by NathanielHill** [comment]
@dagadbm Not trolling, but I honestly don't understand what you mean by folder structure liberty?

The typical way it's done the dotfiles sit in the exact place they would without version control.

I have two bare repos, with working directories of `/etc` and `$HOME` respectively.

In terms of multi-host or other options, you can use branches or conditional logic in scripts.

**Comment by dagadbm** [comment]
i for example have folders for zsh vim tmux etc. and inside those folders i have each dotfile i want.
its just more for organization. and then in the end i run dotbot to symlink those files.

but yes how you have it works as well ofc

**Comment by dagadbm** [comment]
also nice idea having branches per host! hadn't thought of that

**Comment by NathanielHill** [comment]
@dagadbm Well, to each their own I guess.

For me, that's the reason I ultimately switched from `dotbot`. I like not having the duplicate structure, no dependencies except `git`, and no symlinks. 

@anishathalye do you want to close this issue?

**Comment by anishathalye** [comment]
Yeah sure, I can close the issue. I think hongyi-zhao should have enough ideas from this thread. If anyone has follow-up discussion or more questions, feel free to re-open the issue.
