### ISSUE TITLE
Some reviseion on bin/dotbot

### ISSUE THREAD

**Issue by hongyi-zhao** [anishathalye/dotbot#196]
See here:
https://github.com/hongyi-zhao/dotbot/commit/a5bc597a53ed170c9f439ec3b57e69c507ad63b7

**Comment by anishathalye** [comment]
What does this change accomplish? I see that in the patched version, `PYTHONPATH` is being modified if it is already set. For this program, though, does it matter whether we are updating it or replacing it entirely with just the path to this project's directory?

**Comment by hongyi-zhao** [comment]
May be I just want to not touch the original stuff.

Anther thing is that I changed the function inject to path_insert, which may be more meaningful.

**Comment by anishathalye** [comment]
I think unless the current behavior is buggy, let's leave it as-is. Thanks for taking the time to propose this.
