### ISSUE TITLE
My revision on the _default_source() func.

### ISSUE THREAD

**Issue by hongyi-zhao** [anishathalye/dotbot#197]
See here:

https://github.com/hongyi-zhao/dotbot/commit/71ec5e37385c233f226ffac7340f829cc36d914e

```
    def _path_expand(self, path):
        return os.path.expandvars(os.path.expanduser(path))

    def _default_source(self, destination, source):
        destination = self._path_expand(destination)
        home = os.path.expanduser('~')

        if source is None:
            if destination.startswith( home + '/.'):
                return home[1:] + '/' + destination[len(home)+2:]
            else:
                return destination[1:]
        else:
            return source
```

**Comment by anishathalye** [comment]
Can you describe the goal of this change?

**Comment by hongyi-zhao** [comment]
automate the default path name generate for all config files based on the destination names.

**Comment by hongyi-zhao** [comment]
Currently I already using the following form:

```
    def _default_source(self, destination, source):
        destination = destination.strip()
        if source is None:
            if destination.startswith( self._home + '/.'):
                return self._config_root + self._home + '/' + destination[len(self._home)+2:]
            else:
                return self._config_root + destination
        else:
            return source
```

The idea is as follows:

Based on the simple dst --> src mapping rule, construct the install.conf.yaml by a python script via scanning on all of the config files in the self._config_root dir.

**Comment by anishathalye** [comment]
Oh hmm. Could you give an example use? (`install.conf.yaml` file)

**Comment by hongyi-zhao** [comment]
You can use my currently revised version of link.py for seeing this.

The corresponding stuff:

self._config_root which is a directory located in the same directory with install.conf.yaml file : 

$ rg --files config-root/
config-root/etc/apt/sources.list
config-root/etc/apt/sources.list.d/winehq.list.save
config-root/etc/apt/sources.list.d/apt-transport-http.sources.list.save
config-root/etc/apt/apt.conf.d/Dir-Cache-Archives
config-root/home/werner/vim/vimrc



The install.conf.yaml file

```
- clean:
    ~/:
      force: true

- link:
    ~/.vim/vimrc:
    /etc/apt/sources.list:
    /etc/apt/sources.list.d/winehq.list.save:
    /etc/apt/sources.list.d/apt-transport-http.sources.list.save:
    /etc/apt/apt.conf.d/Dir-Cache-Archives:
```

**Comment by anishathalye** [comment]
I think the original commit (linked in the first post) has been deleted, so I can't really test it out. I'm still a little fuzzy on the details, on what exactly config_root is, etc. In any case, I think this might be too much magic for link, so I think we'll keep it as-is for now.

**Comment by hongyi-zhao** [comment]
Thanks for your discussion on this topic.  I latter switched to ansible and deleted the commit by me.

It seems for this type of job, ansible-like tools is more powerful and I want to re-create any wheels.  

Just my point of view.

Regards
