### ISSUE TITLE
Force symlink

### ISSUE THREAD

**Issue by tmcinerney** [anishathalye/dotbot#2]
Would it be possible to add an option to forcibly link a file if the physical file already exists?

**Comment by lliseil** [comment]
Can this please be set up via the yaml version config file?

**Comment by anishathalye** [comment]
It is supported. See this [example](https://github.com/anishathalye/dotbot/tree/c4df1bf2a8633d8da83b4bef6ac3a6c8b4564e59#example).

**Comment by lliseil** [comment]
Thank you. looks I just have some s*it on my eyes.
