### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/dotbot#20]
Even though Dotbot is a fairly simple piece of software (currently ~400 SLOC), it would be nice to have some tests.

A set of shell scripts or something similar could work well to form a little test suite.

**Comment by magicalbanana** [comment]
I can help you with this if you want, I was thinking we could shunit? :dancer:

**Comment by anishathalye** [comment]
It would be nice to have it be a standalone thing, perhaps doing something like what [git](https://github.com/git/git/tree/master/t) does with it's own little [testing library](https://github.com/git/git/blob/master/t/test-lib.sh).

I'm still thinking about what's the cleanest way to test Dotbot when it's doing things like making symlinks (touching the file system) and running shell scripts. I don't know if running stuff directly on the host machine is the best way. Do you have any ideas?

**Comment by magicalbanana** [comment]
I was thinking we can use bats? https://github.com/sstephenson/bats.

I think if you want to test the actual setup you're already talking about BDD testing and we can do that later on too, somewhat a vagrant approach would do or something.

**Comment by anishathalye** [comment]
We could use the framework, but I don't see the need to do so -- most of the tests are going to be pretty specific to Dotbot, and overall, they're going to be pretty simple. An approach like what git does might be better.

I'm thinking that the best way to test Dotbot would be to have a bunch of `install.conf.yaml` configs, and for each config, it would install it and check the file system to make sure the appropriate things were done (and perhaps examine stdout as well to make sure the text output is correct).

I wonder if a tool like [pyfakefs](https://code.google.com/p/pyfakefs/) would be good enough to use?

I guess Vagrant would probably be nicer / more realistic, though. It would be cool to set up Vagrant such that each test is run on a fresh instance of the box. I think a huge sequence of create/destroy operations would be slow when having one per test, but there must be some reasonable way of achieving this effect that's fairly performant.

**Comment by anishathalye** [comment]
Throw away VMs would be nice, but they'd probably be slow to recreate them from scratch per test. Maybe this would be feasible with the use of snapshots.

**Comment by magicalbanana** [comment]
Hmm. I will look into that, I mean we should treat this like a full product and have different tests for each level of acceptance. Lile a unit test (bats) and an integration test (sahara). What do you think?

**Comment by anishathalye** [comment]
My gut feeling is that the code base is too small to need both unit tests and integration tests -- I think integration tests should be enough to cover what we need.

Might be worth thinking about what the bats tests vs sahara tests would look like, though.

**Comment by magicalbanana** [comment]
Hmm, well bats is really for shell. Correct me if I am wrong but your actual code base is in python right? What about we test that instead? :dancer You may have picked up by now I love testing. Haha.

But why not have both? We can start sahara and go with bats after that and if you want I can even do sure for your pyhton code. :dancers:

**Comment by anishathalye** [comment]
Yes, the actual code base is in Python. There is a tiny (~10 SLOC) bash shim to go with that.

And sure, I guess there's no harm in having both. When I get some time, I'll be starting off with sahara.

**Comment by anishathalye** [comment]
Okay, I've finally gotten around to writing a tiny test framework that makes use of Vagrant and Sahara!
(implemented in ef6cedd)

There's some more information in the [readme](https://github.com/anishathalye/dotbot/blob/ef6cedddbf78c5cec2bf39951281c0cb7219a620/test/README.md). The [tests](https://github.com/anishathalye/dotbot/tree/ef6cedddbf78c5cec2bf39951281c0cb7219a620/test/tests) themselves are pretty easy to write.

This is what it looks like when the test suite runs:

![screen shot 2015-05-05 at 8 03 01 pm](https://cloud.githubusercontent.com/assets/3526486/7485320/c2fbbd2a-f361-11e4-8820-2bf8f3c16db8.png)

I've also written 11 [tests](https://github.com/anishathalye/dotbot/tree/ef6cedddbf78c5cec2bf39951281c0cb7219a620/test/tests) as of now, and coverage probably isn't great, but these are good checks to make sure certain bugs have been fixed. I'll add more as time goes on and as new issues are reported (and others feel free to contribute new tests! they're quite easy to implement)

The tests run kinda slowly (because of the whole virtual machine / rolling back per test), but I think that's a good way to have good reproducible tests that can mess with system state.
