### ISSUE TITLE
if-examples

### ISSUE THREAD

**Issue by jdehnert** [anishathalye/dotbot#202]
It would be nice if there were an example or two of how to use the **if** link option.  I have been trying a few things, but they never seem to work.  I'm probably over thinking it, but a simple example may help me and others get it right,

**Comment by anishathalye** [comment]
Ah makes sense, there is no `if` example in the README. Thanks for pointing this out!

A tl;dr on `if` is that it executes what follows in the shell, and it looks at the return value. You can see some examples in the PR: https://github.com/anishathalye/dotbot/pull/173

Btw, happy to try to help you out with your particular config file (it could help me learn how the readme needs to be modified, too). Feel free to post your config file / the particular example you're trying to get working, if you'd like.

**Comment by anishathalye** [comment]
Example added in 8667b75a7338a773ae2d91d7185e29197613ee36.
