### ISSUE TITLE
enable recursive globs in the link tag

### ISSUE THREAD

**Issue by mohkale** [anishathalye/dotbot#215]
I've got a directory containing different themes and I'd like to link all `.colorscheme` files to the programs theme directory. This requires recursive globbing using `**`. See [here](https://docs.python.org/3/library/glob.html).

Eg.

```
- themes
  - an-old-hope
    - an-old-hope.colorscheme
  - foo
    - foo.colorscheme
- config.yml 
```

**Comment by anishathalye** [comment]
By the way, I think you can work around this by writing the glob as `themes/*/*.colorscheme` or similar. But yes, we can enable recursive globs, I'll get around to it in a bit.

**Comment by mohkale** [comment]
Thnx, did not know `themes/*/*.colorscheme` works. That's cool. 😎.

**Comment by anishathalye** [comment]
Also, on second thought, I think it's best to avoid the complexity of recursive globs unless we have a specific and compelling use case for them.

**Comment by eengstrom** [comment]
FWIW, see issue #270 and PR #271.
