### ISSUE TITLE
install dependent to machine

### ISSUE THREAD

**Issue by verajosemanuel** [anishathalye/dotbot#217]
I use dotbot in two machines with different  language configs (English and Spanish)
So, in spanish machine script fails because Pictures folder is non existent but in spanish (Imágenes).
is it possible to specify folders dependent  to machine?

**Comment by anishathalye** [comment]
Yes, with a modification to the install script. See here: https://github.com/anishathalye/dotbot/wiki/Tips-and-Tricks#how-can-i-have-different-groups-of-tasks-for-different-hosts-with-different-configurations

**Comment by anishathalye** [comment]
You can also specify a `if: ` condition on the `link:`, if that makes sense in this context.
