### ISSUE TITLE
Write an automatic dotfiles setup tool

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/dotbot#22]
Setting up Dotbot with an *existing* dotfiles repository is pretty quick.

It would be cool to have a script to make it easier to set up a dotfiles repository with automatic Dotbot integration. The script could be an interactive program that the user guides in creating a git repository, moving existing dotfiles, and setting up an initial `install.conf.yaml` automatically based on the files that were moved.

The script should be mostly automated, basically only asking the user for confirmation when doing things.

**Comment by magicalbanana** [comment]
Is this from what issue? :dancer:

**Comment by anishathalye** [comment]
It's not related to some existing issue, I just thought that this would be nice to have.

It would make adopting Dotbot even easier -- it would be cool if people could do something like `curl https://github.com/.../dotbot-init | sh` and get a dotfiles repo set up in a minute.

**Comment by magicalbanana** [comment]
That would be awesome if this was made possible.

**Comment by Aviator45003** [comment]
I'm setting up my own dotfiles, so am going to write a little bash scriptlet to do it for me, to try and help with this. What kind of interaction are you looking for?

`I found $FILE, want to add it? (Y/n)`

Would something more complicated be better? Less complicated? (Like assume tmux and zsh and bash configs by default, and only ask for other things?)

I think the script would be limited, at least with my scripting abilities, to "dumb" completions like the above. It would be cool if it could get a complicated dotfiles setup done right, but a basic one would be nifty too.

**Comment by anishathalye** [comment]
Yeah, I was thinking of something along those lines. Having the interface be less complicated is better. I think we should prompt for each config, whether or not to add it. There could be a big list of common dotfiles and it could just loop through those (if the files are found).

It would also be cool if it automatically (with prompts) created the dotfiles folder, ran `git init`, added Dotbot as a submodule, (then moved the files over and created the `install.conf.yaml`), and made an initial commit.

No need to implement all that functionality at once -- you're absolutely right in that having even a basic dotfiles setup script would be awesome.

**Comment by Aviator45003** [comment]
Pretty basic, but got me up and running quickly.

**Comment by Aviator45003** [comment]
Finally got repo up and [on git][link]

[link]: https://github.com/Aviator45003/easy-dotfiles

**Comment by anishathalye** [comment]
Nice! Any plans or ideas on how to publicize this?

**Comment by Aviator45003** [comment]
I'm telling friends who don't yet have dotfile repositories.

I don't have a blog. I don't have many friends who are nerdy enough to know what dotfiles are. My market is really people who don't yet have dotfile repositories. I don't know how to reach that market.

If you have any ideas, that would be pretty cool.

**Comment by joshblum** [comment]
showhn?

**Comment by anishathalye** [comment]
Yeah, I think showhn is a good idea. And probably /r/commandline as well.
I think it'll be more effective if there's a little more detail in the readme (or perhaps even a blog post or something).

**Comment by Aviator45003** [comment]
If anybody wants to PR the readme, I would be grateful.

**Comment by anishathalye** [comment]
I can look at adding stuff to the readme in a couple days.

If you want to, sure. I could also write up something on my blog (I've written about [similar things](http://www.anishathalye.com/2014/08/03/managing-your-dotfiles/) before).

**Comment by anishathalye** [comment]
This is [done](https://github.com/Aviator45003/init-dotfiles), so I'm going to go ahead and close this issue now.
