### ISSUE TITLE
What is the purpose of `~/.dotfiles:` in README.md's example?

### ISSUE THREAD

**Issue by jennydaman** [anishathalye/dotbot#224]
https://github.com/anishathalye/dotbot/blob/f5e019105ec5a70a71d5afa78dc44baa0e87b721/README.md#full-example

```yaml
- link:
    ~/.dotfiles: ''
```

**Comment by anishathalye** [comment]
That's a good question, perhaps I should amend the README to explain this.

Suppose I clone my dotfiles repo in `/home/anish/stuff/src/dotfiles`. This will create a symlink `~/.dotfiles -> /home/anish/stuff/src/dotfiles`. This is convenient for having other stuff reference contents within the dotfiles directory. For example, I have a `bin/` directory in my dotfiles, where I keep shell scripts, and then I add `~/.dotfiles/bin` to my `$PATH`.

**Comment by jennydaman** [comment]
Thank you for the explanation! With that line, `./install` throws a warning if the repo is cloned to `~/.dotfiles` (as also suggested in README.md) so it was confusing to me.

**Comment by anishathalye** [comment]
Thanks again for raising this issue -- I removed the confusing example from the documentation in 8f136ee73f4231034d6a5af3a7bf23dc3f28400a (it was confusing without the explanation, and I figured that it wasn't worth explaining in the readme).
