### ISSUE TITLE
Dotbot add cronjob

### ISSUE THREAD

**Issue by fundor333** [anishathalye/dotbot#230]
My working configuration has some cronjob which I need to add when I reinstall the system. 
There is a easy way to add cronjob support for Dotbot? A way to add cronjob whith some command into the config?  
Like a - Cron command?

**Comment by wren** [comment]
I don't think there's dotbot support for cron, but you can use a shell command to install your crontab from a file with: `crontab filename.txt`.

**Comment by anishathalye** [comment]
There is currently no special support for interacting with cron in Dotbot. As a simple workaround, you could do it through `shell:` -- see advice on the internet for interacting with cron programmatically.

If you're feeling ambitious, you could contribute a cron [plugin](https://github.com/anishathalye/dotbot/wiki/Plugins) :)

**Comment by fundor333** [comment]
I make a plugin for crontab. Can I add to the plugins list ?
Here the link to the repo https://github.com/fundor333/crontab-dotbot

**Comment by anishathalye** [comment]
Yes, please go ahead. Anyone can edit the wiki.

**Comment by fundor333** [comment]
Done thanks!
