### ISSUE TITLE
allow overrides for hosts

### ISSUE THREAD

**Issue by tessus** [anishathalye/dotbot#233]
Years ago I wrote my own bootstrapping scripts in bash, but then I found this a while back. I had wanted to use python to parse yaml files for better configuration of the process, but then I thought why should I reinvent the wheel.
You really did a great job and I'm very happy with your project.

However, I think there's a feature that you might also find interesting.

You currently can achieve the same thing, but involves more work in the config. Therefore I suggest an additional option in the config file.

Something like the following:
```
- defaults:
    override: true
        path: hosts
```

In this case, when doing the `link` step, it would check in the directory `hosts/<hostname>` for a file with the same name first. Is one found, it would use that one instead.

Currently this can be achieved by using `if`, but that would have to be done for every single file and one would have to create almost the same entry for every single hostname.

This feature would make it a lot easier to use a single repository for bootstrapping several machines with different files for different hosts.

Many files are most likely the same across the board, but there can also be a lot of files that differ depending on the hostname of the machine you bootstrap. On the other hand my idea would not really help in cases where you want to add config files that are only specific for a certain machine. But such a case is less common and can be done in the config file explicitly.

What do you think? Does this make any sense? I'm really busy these days, but I think this could be added with a few lines of code. Is this something you would accept as a PR or implement yourself?

**Comment by anishathalye** [comment]
This is an interesting idea. It seems like it could make machine-specific configs simple for people who have per-host settings.

The way I personally do per-machine configs is with a [repo](https://travis-ci.com/github/anishathalye/dotfiles-local) that has per-machine branches. I actually don't have a one-to-one correspondence between hostnames and configs, so being able to manually select the branch is helpful for me.

I wonder how often users have meaningful hostnames, and have per-host configs as opposed to a looser correspondence (like mine). I think at the very least, if we were to include a feature like the one you propose, we'd want to have a command-line argument to override the hostname.

The problem of per-host customization seems to be a somewhat common pain point for users. My solution (a second "dotfiles-local" repo, with per-machine branches) has been working all right for me, but perhaps it's a good time to revisit support for alternative strategies. People have previously suggested templating as a feature that could provide similar end results. Your idea seems like a pretty clean solution as well, for the case of per-host config.

Recently, a lot of my free time had gone into the release of [another project](https://github.com/anishathalye/periscope), but now that I'm done with that, I'm hoping to spend my next chunk of free time reviewing all the feature ideas for Dotbot, doing a user study to see how people are using Dotbot in the wild, and consider whether we should do a "2.0" release that can solve a lot of problems without worrying about backwards compatibility. I think your suggestion could potentially fit into that.

**Comment by anishathalye** [comment]
Closing due to age / inactivity; not currently planning on adding this feature.
