### ISSUE TITLE
Already have a `install` dir in the root of my dotfiles dir

### ISSUE THREAD

**Issue by tddschn** [anishathalye/dotbot#239]
I'm new to dotbot and is trying to follow the getting started guide in the readme, and stuck at this step:
```
cp dotbot/tools/git-submodule/install .
```
As I already have a `install` dir in the root of my dotfiles dir, and I don't want to rename the `install` dir to avoid breaking some of the scripts wrote that uses the `install` dir.

What should I do? Thanks!

**Comment by anishathalye** [comment]
The name `install` isn't anything special. You can copy/rename the install script to anything you like, e.g. `setup`, and then you'll call it with `./setup` rather than `./install`.

**Comment by tddschn** [comment]
Thanks for your help! :)
