### ISSUE TITLE
bug: module "yaml" not found

### ISSUE THREAD

**Issue by wongjiahau** [anishathalye/dotbot#242]
I need to run the following before I can successfully run `./install` :
```
python -m pip install PyYAML
```

**Comment by anishathalye** [comment]
This shouldn't be necessary (https://github.com/anishathalye/dotbot/issues/19#issuecomment-84461869). How are you installing Dotbot -- as a submodule? Dotbot itself includes PyYAML as a submodule (https://github.com/anishathalye/dotbot/tree/master/lib), so it shouldn't be necessary to install it separately. Do you have any kind of unusual system configuration, or any other info that would help me figure out why you had to do this?

**Comment by wongjiahau** [comment]
Here's the step to reproduce it:
Assuming you have docker
```
docker run -it ubuntu /bin/bash
apt-get update
apt-get install -y git
git clone https://github.com/wongjiahau/my-neovim-config.git
cd my-neovim-config
./install
```
After running the step above you should see the "yaml" module missing error.

I'm not sure if I set up dotbot correctly for my dotfiles but I remembered I follow the README's  instruction.

**Comment by anishathalye** [comment]
It does not look like you've added Dotbot as a submodule; rather, you've copied the directory, and the copy is missing the submodule (https://github.com/anishathalye/dotbot/tree/master/lib exists, but there is no corresponding "lib" directory in your copy).

I'd recommend `git rm -r dotbot && git submodule add https://github.com/anishathalye/dotbot` (along the lines of the [README instructions](https://github.com/anishathalye/dotbot#integrate-with-existing-dotfiles)), so you'll have Dotbot as a submodule.

**Comment by wongjiahau** [comment]
After running:
```
git rm -r dotbot && git submodule add https://github.com/anishathalye/dotbot
```
The problem is indeed fixed. 

However, if I follow the commands from the README:
```sh
cd ~/.dotfiles # replace with the path to your dotfiles
git init # initialize repository if needed
git submodule add https://github.com/anishathalye/dotbot
git config -f .gitmodules submodule.dotbot.ignore dirty # ignore dirty commits in the submodule
cp dotbot/tools/git-submodule/install .
touch install.conf.yaml
```
I end up cloning the whole dotbot submodules in my repository, and `git status` reveals a lot of added files, namely:
```
Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   .gitmodules
	new file:   dotbot

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .gitmodules

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	install
	install.conf.yaml
```
And out of naiveness I staged everything and committed them. 

So I suspect there are some **missing commands** required before committing?

**Comment by anishathalye** [comment]
Staging and committing everything is the right thing to do... I'm not sure how you ended up with a copy rather than submodules.

This is what happens when I copy-paste the instructions:

![Screen Shot 2020-10-29 at 8 32 42 AM](https://user-images.githubusercontent.com/3526486/97574334-70fddd00-19c1-11eb-8203-8cba059401c1.png)

**Comment by wongjiahau** [comment]
@anishathalye I'm convinced that I did something wrong during the setup, I tried the commands above with a new repository and it this issue does not happen in docker ubuntu.
Thanks for the help!

**Comment by anishathalye** [comment]
Glad it's sorted out now :)
