### ISSUE TITLE
Linking with glob strips leading '.' from link name

### ISSUE THREAD

**Issue by etkeys** [anishathalye/dotbot#244]
## Enviornment

OS: Ubuntu Mate 20.04.1
Python version: 3.8.2
dotbot version: 1.17.1 (yaml: 5.3)

## Setup

Given a repository with this structure:

```txt
home/.bashrc
home/.profile
home/.vim
install
install.conf.yaml
```
with this `install.conf.yaml`:

```yaml
- defaults:
    link:
        create: true
        force: true
        relink: true

- link:
    ~/:
        path: home/.*
        glob: true
```

## Execution

running `./install -v` produces this output:

```txt
Globbing with path: home/.*
Globs from 'home/.*': ['home/.vimrc', 'home/.profile', 'home/.bashrc']
Creating link ~/vimrc -> /home/erik/.dotfiles/home/.vimrc
Creating link ~/profile -> /home/erik/.dotfiles/home/.profile
Creating link ~/bashrc -> /home/erik/.dotfiles/home/.bashrc
All links have been set up

==> All tasks executed successfully
```

Running `ls -l ~` confirms that the link names do not have the leading '.'. I
would expect the link name to keep the leading '.' (e.g. `~/.vimrc`). I realize
that I can specify the links for these files individually, but this approach
is more work to maintain.

## Remarks 

If I change `path: home/.*` to be `path: home/*` based on the example from the
documentation, python glob module ignores files that start with '.'. Looking
more at how link.py works, it seems the problem might [behere](https://github.com/anishathalye/dotbot/blob/master/dotbot/plugins/link.py#L78-L80),
specifically how `glob_item` is set. I haven't put the code through a debugger
yet to confirm, but I think adding a check if `glob_base` has trailing '.',
then remove trailing '.'. This would cause `glob_item` to have the leading '.'.
I'll have some time tomorrow to try this.

**Comment by anishathalye** [comment]
Fixed by #245
