### ISSUE TITLE
As a plugin creator, I would like the ability to access what cli options were passed when dotbot was initial invoked.

### ISSUE THREAD

**Issue by etkeys** [anishathalye/dotbot#249]
### A: Plugin calls dotbot again as sub-process

Ref [dotbot-sudo](https://github.com/DrDynamic/dotbot-sudo). A plugin might have need to run dotbot again as a sub-process to do a cool thing. Some of the options passed when initially invoked could still be applicable in the sub-process as well (e.g. `--vebose` (#104), `--plugin-dir`, `--force-color`).

*dotbot-sudo* runs a script to deal with only those directives given under it, but I can imagine a scenario where I would want to run dotbot using a different config file. For example, *.dotfiles* repo also installs *.dotfiles_local*

### B: Plugin calls something else as a sub-process

To extend the previous section a bit more. What if a plugin calls some other application as a sub-process that can print output of varying levels. Let's say we want to pass a `--verbose` flag to this sub-process only if *dotbot* was called with `--verbose`.

## Case 2: Plugin handles mutually exclusive directives

I had a really good scenario for this, but then I found out that `--exclude` exists and then there's [cf36bb](https://github.com/anishathalye/dotbot/commit/cf366bbf6676d1c95f412eb514509f16322b5c9c)...so I'll just keep that to myself for now.

## Case 3: The future

Who know what the future holds, am I right? What if more cli options get added that plugins could leverage? I'll concede this point as it's unlikely that 1.x will implement such a cli option, but maybe something to consider for 2.0?

## Current workaround
From what I've been able to determine, a plugin could just examine `sys.argv` to determine what cli options were passed. By the time the plugin is used, the options have been validated and should be safe to use. This seems hacky though. The core application validates/manipulates the cli options to setup the appropriate context. A plugin shouldn't circumvent the work done by core and possibly damage the current context.

Also, what if using just `sys.argv` becomes improper? Either a new method is used or `sys.argv` is augmented with addition data? A plugin would be unaware of this condition.

**Comment by etkeys** [comment]
Maybe exposing the cli options isn't good? Plugins would have to keep up with argument parsing and it's unstructured. Maybe exposing `options` generated [here](https://github.com/anishathalye/dotbot/blob/master/dotbot/cli.py#L52) would be a better way to go?

**Comment by anishathalye** [comment]
Merged #250
