### ISSUE TITLE
As a test runner, I would like the ability to toggle test debug output without having to place DEBUG=true inside the test files.

### ISSUE THREAD

**Issue by etkeys** [anishathalye/dotbot#252]
Been running the tests and adding some new ones. The need to add `DEBUG=true` at the top of the file to run in order to see extra output is bothersome and subject to being [accidentally committed](https://github.com/anishathalye/dotbot/compare/62c3a2d850deab3e6c78d301a2ce60b714563391..0ba45763d938c26b81029a8493e26864314da7bd). Now suppose I made a change that broke other tests I wasn't looking at. I'd have to modify those test files if I wanted to see the extra output.

It'd be nice to pass a flag to `test` that would that define `DEBUG=true` for all files being tested at that time.

Assuming that the flag gets passed down all the way to `driver-lib.bash:run_test()`, would changing the function from
```bash
run_test() {
    # ...
    if (cd "${BASEDIR}/test/tests" && DOTBOT_TEST=true bash "${1}"); then
        pass
    else
        fail
    if
}
```
to
```bash
run_test() {
    # ...
    if -n "$1" ; then
        export DEBUG=true
    fi
    if (cd "${BASEDIR}/test/tests" && DOTBOT_TEST=true bash "${1}"); then
        pass
    else
        fail
    if
}
```

be sufficient?

Or maybe put `export DEBUG=true` at beginning of `test` before `driver-lib.bash` is sourced?

**Comment by anishathalye** [comment]
This is a great idea, not sure why we didn't do this before! Implemented in dac7a9b.
