### ISSUE TITLE
Global folder

### ISSUE THREAD

**Issue by inigochoa** [anishathalye/dotbot#254]
Hi!

I'm trying to create a global folder dotfiles to be the default folder for dotbot to look for the files. I've tried with a `defaults link path` variable but it does not search inside the dotfiles folder. Is it possible to store al my dotfiles inside a folder?

Thank you!

**Comment by etkeys** [comment]
Hello!
Could you provide more detail about what you're trying to do? Sample directory structure, desired outcome, etc.

It sounds like you have a repo that looks likes this
```txt
dotfiles
|-- dotfiles_global
|   |-- config
|   |   `-- App1
|   |       `-- conf
|   |-- bashrc
|   |-- profile
|   `-- vimrc
|-- other_dir
|   |-- file1
|   `-- file2
|-- install
`-- install.conf.yaml
```
And instead of defining a link section that looks like
```yaml
- link:
    ~/.bashrc: dotfiles_global/bashrc
    ~/.profile: dotfiles_global/profile
    ~/.vimrc: dotfiles_global/vimrc
    ~/.config/App1/conf:
        path: dotfiles_global/config/App1/conf
        create: true
```
You'd like a link section that looks like
```yaml
- link:
    ~/.bashrc: bashrc
    ~/.profile: profile
    ~/.vimrc: vimrc
    ~/.config/App1/conf:
        path: config/App1/conf
        create: true
```
Essentially, use some prefix `<prefix>` as the beginning of all `path` parameters for `link`. Is this correct?

**Comment by etkeys** [comment]
Possibly related to #233

**Comment by inigochoa** [comment]
Hi!

What I'm trying is:

Structure
```bash
dotfiles
|-- dotbot
|-- dotfiles
|   |-- folder
|   |   |-- fileX
|   |   `-- fileY
|   |-- bashrc
|   |-- profile
|   `-- vimrc
|-- install
`-- install.conf.yaml
```
And somehow, in the config tell dotbot that all my files are in the `dotfiles` subfolder.

I tried:

```yaml
- defaults:
    link:
        create: true
        path: dotfiles
        relink: true
```
I also tried with `/`, `/*`.

I'm trying to avoid adding the path in each link element.

Thank you!!

**Comment by etkeys** [comment]
Currently, `link` does not check `defaults` for a `path` value and the only means to avoid having to specify a value for `path` is using *Implied sources* approach. Implied sources is limited such that dotbot will only match on the directory/file basename (sans leading `.`) which means that your source directory/files must exist in the same directory as `install`. Doing this adds clutter to the root of the repo, so I get why you've gone with the directory structure you have.

I'd suggest using link's `glob` parameter, but based on how your repo is structured, you're likely going to be limited the same as me (see #244 and #247). It could help some, but you're still going to have to provide a path for each link item.

Speaking from my own point of view, I could see the ability to temporarily change the base directory used to search for link sources being handy. Not sure if @anishathalye would want to consider it for a later version. But even if it were a feature, I don't know how useful it would be. I don't think there is a good way to infer how sources in a directory structure that is more than one level deep should be mapped to their destination.

**Comment by inigochoa** [comment]
Thanks @etkeys for the reply. As I do not have many dotfiles yet, I think I will add the folder name to each link. It's a bit dirty, but it is what it is.

**Comment by anishathalye** [comment]
What is the reason for having a dotfiles folder within the dotfiles folder? Can you not flatten it by one level, for example [like this](https://github.com/anishathalye/dotfiles)?

**Comment by anishathalye** [comment]
Also, if you do want the `dotfiles` folder, you can edit your install script to set that as the base directory when invoking Dotbot. So [this line](https://github.com/anishathalye/dotfiles/blob/master/install#L15) would turn into something like

```diff
- "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
+ "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}/dotfiles" -c "${CONFIG}" "${@}"
```

**Comment by inigochoa** [comment]
Thank you very much @anishathalye for the reply!! That was exactly what I was looking for. It could be said that I have a little OCD with the folders and I see it better organized like that. Scripts on the root, dotbot in one folder and dotfiles in another. Thank you very much again!!
