### ISSUE TITLE
Add symlink tool seperately

### ISSUE THREAD

**Issue by shivapoudel** [anishathalye/dotbot#26]
Read the yaml or json file from bash and use `ln -s ...` to create symlink for windows. 
Demo: https://github.com/shivapoudel/symlink

**Comment by anishathalye** [comment]
I'd like to avoid the additional complexity of using an external tool to create symlinks. If there's a cleaner way to do it, I'd be open to it.

Also, I don't know how much of a need this is. I think the majority of Dotbot users run Linux or Mac OS.
