### ISSUE TITLE
No CHANGELOG

### ISSUE THREAD

**Issue by martindzejky** [anishathalye/dotbot#274]
Hello! 👋 

I'm using `dotbot` in my dotfiles as a git submodule. From time to time, I update it to the newest version, which often pulls in new tags and commits. It would be super helpful if the project included a *CHANGELOG* file (or use Github releases) so I can see what has changed and whether there's any new helpful feature I could use in my dotfiles. What do you think?

**Comment by anishathalye** [comment]
The changelog is here: https://github.com/anishathalye/dotbot/wiki/Changelog

Do you think it would be helpful to include a link somewhere for discoverability?

**Comment by eengstrom** [comment]
I for one think putting the typical `CHANGELOG` into the source tree is helpful.  You can avoid maintaining the WIKI version then, pointing instead at the source tree.

**Comment by anishathalye** [comment]
I don't have strong opinions about this, but that seems pretty standard. Done in aa9335089b54475940bb41e2a4eed38affeb5916.

**Comment by martindzejky** [comment]
Amazing, thanks! :)

One benefit to having the changelog in the source repository is that when I use `dotbot` as a Git submodule, I can update it and then just open and read the local `dotbot/CHANGELOG` file.
