### ISSUE TITLE
Discrepancy in install-profile/install-standalone scripts on Tips & Tricks page 

### ISSUE THREAD

**Issue by williamwong** [anishathalye/dotbot#283]
On the Tips & Tricks page in the wiki, the newly updated `install` scripts have the following line to point to the path of the dotbot bin:

`cmd=("${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" -c "$configFile")`

This works only _if_ you installed the dotbot submodule inside the `/meta` folder, or if you are starting from @ecarlson94's great [dotbot-template](https://github.com/ecarlson94/dotbot-template) repo. However, if you are just following the instructions on the main README, you likely added the dotbot submodule directly to the root of the repo, in which case you'd have to modify the above line to:

`cmd=("${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" -c "$configFile")`

to ensure that the dotbot binaries can be located correctly.

Fwiw, I actually like the idea of having the submodule in the `/meta` folder, so maybe the best solution here is to make a note of it to ensure that the dotbot submodule is in the right location, with maybe some small instructions on how to relocate a git submodule if necessary?

**Comment by anishathalye** [comment]
Thanks for pointing this out, and for suggesting that we include instructions on how to move a git submodule. Do you think [these updated instructions](https://github.com/anishathalye/dotbot/wiki/Tips-and-Tricks#new-install-scripts) are sufficiently descriptive?
