### ISSUE TITLE
Link from source to unknown path

### ISSUE THREAD

**Issue by typkrft** [anishathalye/dotbot#285]
Sorry, it's very possible I'm not understanding something. My understanding is that the glob feature just applies to the source not the destination being linked to. Maybe a script of some kind would work. 

In macOS the Firefox `userChrome.css` is in `$HOME/Library/Application\ Support/Firefox/Profiles/*/chrome/userChrome.css`. This folder varies I believe and this would be useful for a couple of reasons:
  1. to obviously get the path
  2.  the ability to link the userChrome.css to multiple profiles simultaneously. 

Inside of the Profiles directory are 3 directories for me`2j7r4oqe.default  efhnzow1.default-release  v775fdai.default-nightly`

**Comment by anishathalye** [comment]
Yes, you are right, the glob just applies to the source, not the destination. I'm not sure what the semantics should be if globs were to be supported in the destination. How often does this come up, where the exact destination path is unknown? And in such situations, does one usually want the file linked to a particular matching path, or _all_ matching paths?

**Comment by typkrft** [comment]
Hey thanks for the response. Great program by the way. I wouldn't say it comes up often, but I do know that customizing Firefox userChrome is pretty common. macOS seems to do a few things in non standard ways too. It may also be useful for working those who work with Selenium, where users have a number of profiles. Or if there a number of different versions of a program you are working with. There are ways around this specific problem I'm having, but its pretty messy. Basically I have to delete all the profiles with a shell command or do some complex awk/def work, regenerate the profile.ini with an echo command, open the browser, kill the browser, move the profile, add the needed files. Where just using shell expansion would completely resolve this. I don't know the inner workings of yaml or anything but maybe an extra parameter that either lets you define the path as it would be expanded to I. sh would work. Or expansion: true. It could be useful doing all or targeting specifics. But using shell expansion would allow for either of these scenarios reasonably well.

**Comment by ldorigo** [comment]
Just adding my voice to this request - with a very similar usecase: I want to sync my e-mail filters in thunderbird (which shares most of the structure of firefox), and exactly like @typkrft describes, the filters are also inside a profile that includes a machine-generated name that is different on each computer. 

An alternative way to solve this would be to be able to define variables in the yaml file - so I could do something like 

`profile=( ~/.thunderbird/*.default-release )`

and then:

```
- link: 
  ~/.thunderbird/$profile/filters: thunderbird/filters
```

**Comment by erwin** [comment]
As @typkrft mentioned, I would like to use this for `userChrome.css` with dotbot.

Also, KDE Connnect has a similar format... 

```
/.config/kdeconnect/<device ID in hex>/kdeconnect_runcommand/config
```

In my dotbot config, I would like to write:

```
link:
  /.config/kdeconnect/*/kdeconnect_runcommand/config
    path: kdeconnect
    glob: true
```    

And have this glob expanded like with shell globbing. You could apply the "glob: true" flag to both dest and path.

Just a second example of where globbing on the DESTINATION would be useful.

**Comment by anishathalye** [comment]
Closing due to age / inactivity. I don't currently plan to implement this feature.
