### ISSUE TITLE
Dotbot does not link files on Ubuntu 21.04

### ISSUE THREAD

**Issue by koenverburg** [anishathalye/dotbot#286]
Hi, 

For some reason, dotbot is acting weird on Ubuntu 21.04 installed on a laptop but also inside a docker container.
If I run it with `sudo bash ./install` from fish and from bash using the same command, I get the same result as shown below.

It works on Windows 10 and Macos.

![Screenshot from 2021-08-10 09-43-28](https://user-images.githubusercontent.com/10489237/128828524-f6dc248c-9a20-44c7-8a6b-4930ba619123.png)

Small note: the config shows that the links are commented out, locally they are not.

Files:
- [ubuntu.config.yaml](https://github.com/koenverburg/dotfiles/blob/main/ubuntu.config.yaml)

**Comment by anishathalye** [comment]
I wouldn't recommend running Dotbot with sudo (then all your symlinks will be owned by root).

Could you try running `./install -v` for verbose debug output, and paste the messages here?

Also, could you share the original `ubuntu.config.yaml`, the exact one you are trying on your local machine, without the comments? (incorrect spacing can break YAML, so I wanted to check that for the original file)

**Comment by koenverburg** [comment]
Running it with `-v` showed what was wrong, and like you said it had to do with indenting. It's all resolved now. This is the [config](https://github.com/koenverburg/dotfiles/blob/main/ubuntu.config.yaml) ended up pushing.

I also fixed my permissions on Ubuntu to run it without sudo, but on Macos I still need to run it with sudo but that can be caused by the software installed by my employer.

Anyway, thanks for the quick response, have a great day!
