### ISSUE TITLE
Bash dotbot files library

### ISSUE THREAD

**Issue by gtrabanco** [anishathalye/dotbot#293]
Hi.

Not sure about a library I made could be useful for this project or does not.

I have made a library that can handle yaml files used by dotbot so you can manipulate a directive, read a value, delete and of course create it. I use it in my scripts for those times should change something in my dotbot configuration file and with the idea of making a script to move files to inside my dotfiles but keeping the link outside of this (useful to save editors or streamdeck configuration) but I did not finish this script anyway it can be used to whatever.

You can view the library here:
- https://github.com/gtrabanco/dotSloth/blob/HEAD/scripts/symlinks/src/dotbot.sh

Sorry if issue its not best idea for this purpose but I am not sure if you are interested in add this library to the project or could be helpful for anyone.

Regards.

**Comment by anishathalye** [comment]
That looks interesting. I don't have a need to integrate it into the main Dotbot directory. If you think it will be useful, feel free to add a pointer to the script in the [Dotbot wiki](https://github.com/anishathalye/dotbot/wiki) (anyone can edit), perhaps in the "Tips and Tricks" section.
