### ISSUE TITLE
Add commenting feature in the profile files

### ISSUE THREAD

**Issue by Vafa-Andalibi** [anishathalye/dotbot#298]
I believe anyone setting up a profile will need to do some testing for each configuration in the profile. 
Adding the commenting feature in the profile, helps a lot otherwise one has to constantly add/remove config names.

**Comment by Vafa-Andalibi** [comment]
This `exit()` was the culprit: 

https://github.com/anishathalye/dotbot/blob/769767c129c8f26eb66dca06dfa4a1bddbac8a9e/dotbot/cli.py#L162

Why should this be here? isn't logging it sufficient?

**Comment by kurtmckee** [comment]
@anishathalye I recommend closing this issue. It doesn't seem to be a clear feature request, and hasn't been addressed for over a year.
