### ISSUE TITLE
Copying the SSH-folder doesn't work with the installer

### ISSUE THREAD

**Issue by tofagerl** [anishathalye/dotbot#31]
So I added a simple shell command,  [cp ssh -af ~/.ssh, Copying SSH-folder] in order to copy it instead of symlinking. (Long story.)

However, the command fails. I've tried the command in the normal shell, and it works fine. What could be the problem?

**Comment by anishathalye** [comment]
Hmm, that command seems to work on my computer...

Could it be a typo in the config file or something? What happens if you replace the command with something else like `touch ~/testfile`?

Also, I'm not sure if your dotfiles are public, but if you don't mind sharing your `install.conf.yaml` and/or dotfiles repo, I'd be happy to take a look and see if I can figure out what's going on.

**Comment by anishathalye** [comment]
For reference, here's my `.install.conf.yaml`:

```yaml
- shell:
  - [cp ssh -af ~/.ssh, Copying SSH folder]
```

**Comment by tofagerl** [comment]
All other commands work, including chmoding the same dir 0700.
It's not public, and won't be, but the YAML file looks like this: 
````yaml
- clean: '~'
- link:
    ~/.vimrc: vimrc
    ~/.tmux.conf: tmux.conf
    ~/.zshrc:
      force: true
      path: zshrc
    ~/.gitconfig: gitconfig
    ~/.zprezto: prezto
    # ~/.zsh-antigen: zsh-antigen
    ~/.zshenv: zshenv
    ~/.zprofile: zprofile
    ~/.zpreztorc: zpreztorc
    ~/.zlogin: zlogin
    ~/.zlogout: zlogout
- shell:
    - [cp ssh -af ~/.ssh, Copying SSH-folder]
    - [chmod -R 0700 ssh ~/.ssh, Making SSH-folder read-only]
    - [git submodule update --init --recursive, Updating the submodules]
````

**Comment by tofagerl** [comment]
Is there a switch to install/dotbot that could output errors to stdout?

**Comment by anishathalye** [comment]
Oh it looks like the `cp ssh -af ~/.ssh` operation will copy the `ssh` folder into `~/.ssh/ssh` if the `~/.ssh` folder already exists.

And yes, there is a switch. You can do this:

```yaml
- shell:
  -
    command: cp ssh/ -afi ~/.ssh/
    message: Copying SSH folder
    stdout: true
    stderr: true
    stdin: true
```

**Comment by tofagerl** [comment]
And that worked! Thanks a lot!

**Comment by tofagerl** [comment]
Interesting... If I put it back to the normal style it doesn't work, but if I keep the stdout, stderr and stdin it works. 

NO IDEA why, but it solves it for me, so I'm keeping it.

**Comment by anishathalye** [comment]
Oh what... that's really strange, I have no idea why the result would be affected by that. Well, I'm glad it works!

Btw, for future reference, Dotbot by default closes stdin/stdout/stderr, and you can use the extended syntax if you need any of those features.
