### ISSUE TITLE
[BUG] Tips and Tricks -> install-profile

### ISSUE THREAD

**Issue by darsh12** [anishathalye/dotbot#319]
Hi,
I have been using an old script of the install-profile, however once I updated the install-profile script, the script broke. 

![image](https://user-images.githubusercontent.com/16546412/181395528-efd2827c-8f9e-4d84-8ea9-c1fb043a7a0a.png)

The script initially assumes that the dotbot is located in the `meta` folder. But once we progress in the script, the git submodule commands are looking for the `dotbot` dir to update.

![image](https://user-images.githubusercontent.com/16546412/181395857-9ff262a9-b936-4b6a-862b-e2864a6cc5cf.png)
 

As shown in the image, first we `cd` to the base directory, and the `git submodule` is looking for the `dotbot` directory in the base directory which does not exist because it is in the `meta/dotbot` dir.

### 1
```bash
git -C "${BASE_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${BASE_DIR}"
```

### 2
```bash
git -C "${META_DIR}/${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${META_DIR}/${DOTBOT_DIR}"
```

**Comment by anishathalye** [comment]
Nice catch! Anyone is allowed to modify the wiki. Would you like to make your corrections directly?

**Comment by darsh12** [comment]
Thank, I just edited the wiki with fix 1.
