### ISSUE TITLE
Dotbot from PyPI just won't work under Windows10

### ISSUE THREAD

**Issue by devholland** [anishathalye/dotbot#323]
Hello,

Excuse me if I'm doing something wrong, it's the first time I'm trying to use Dotbot and I just can't get it to work under Windows. I installed it via pipx:

```bash
pipx install dotbot
```

I created a test file with `Out-File test.txt` and a `install.conf.yaml` with the following content:

```yaml
- link:
  ~/AppData/test.txt: test.txt
```

When I try to run Dotbot with `dotbot -c install.conf.yaml` I always get the following error:

```bash
Linking failed ~/AppData/test.txt -> C:\repos\dotfiles\test.txt
Some links were not successfully set up

==> Some tasks were not executed successfully
```

Any idea what I'm doing wrong? It won't work neither in PowerShell nor in Git Bash.

**Comment by kurtmckee** [comment]
@devholland You're not doing anything wrong. I encountered the same issues and created PR #313 to address these issues and overhaul the testing so the tests can run on all supported platforms.

For now, you can use git to clone my repo and checkout my branch:

```powershell
# Clone the repo and checkout the branch with fixes.
git clone git@github.com:kurtmckee/dotbot.git
cd dotbot
git checkout test-on-windows-issue-309

# Build and install the package.
python setup.py sdist
pipx install dist\dotbot-1.19.0.tar.gz
```

**Comment by anishathalye** [comment]
Hi! I do intend to merge #313 and related PRs once I get a chance to look at them. Just been insanely backlogged recently, sorry for the delays. Like Kurt said, as a workaround, you can use his branch for now.

**Comment by kurtmckee** [comment]
No intended pressure from my side, @anishathalye! Getting swamped is something everyone understands. :smile:
