### ISSUE TITLE
Drop support for python 2.7

### ISSUE THREAD

**Issue by aqeelat** [anishathalye/dotbot#338]
I would like to work on this issue

**Comment by anishathalye** [comment]
What do you mean by dropping support for Python 2.7? The code is already Python 2.7 compatible, without much weird compatibility code. I don't want to remove functionality without good reason.

In fact, adding back Python 2.7 testing to CI would be ideal (I got lazy in 53b3781fbb6d926ada37f511b21897290df93df8).

**Comment by kurtmckee** [comment]
I agree with this request, insofar as the project documentation and test suite drop all claims for Python 2.7 support.

The loss of Python 2.7 support in CI needs to be a clear death knell, not a challenge to find an alternate solution. Unless CI support can be restored, the project needs to drop claims of support for Python 2.7 for lack of compatibility testing on incoming PRs.

**Comment by anishathalye** [comment]
Added back Python 2.7 testing in 712b30a44508dacba8d2f250753035f168e0812b. Is there anything else related to Python 2.7 support that we need to discuss, or should we close this issue?

**Comment by kurtmckee** [comment]
It is possible to document that "dotbot 1.19.2 / commit 712b30a is the last version to officially support Python 2.7" and then allow the project to move forward.

Ongoing Python 2.7 support feels like it's a point of pride. I recommend deciding and documenting whether Python 2.7 will always be supported, or under what conditions dotbot will stop targeting Python 2.7 (like "_X_ years after 2.7 EOL", or "after _Y_ distro is EOL", etc). That will help users and developers understand the situation, and will make it easier to address tickets like this.

This ticket can be closed, but please consider making a decision about Python 2.7 and documenting it. I hope that the above will be taken as a recommendation, not a condemnation. I really do appreciate your work on dotbot!

**Comment by anishathalye** [comment]
> Ongoing Python 2.7 support feels like it's a point of pride.

It's also a practical matter for me — I use many machines, and some of them are running old OSes with only Python 2 installed.

I don't want to _remove_ Python 2.7 support without good reason (the support is already there, and there is no burden for leaving it in at the moment). I think a good time to consider removing Python 2.7 support would be whenever a substantial new feature is being updated where Python 2.7 compatibility is difficult. Otherwise, I think there is no hurry.

**Comment by kurtmckee** [comment]
> I use [...] old OSes with only Python 2 installed.

That helps clarify the ongoing support. Thanks!
