### ISSUE TITLE
[Request] force - does it overwrite any file?

### ISSUE THREAD

**Issue by Ploppz** [anishathalye/dotbot#34]
Hi.
In the YAML configuration file, if you say `force: true`, does that currently override the desination no matter what it is? I would like it to overwrite any existing symbolic link, but still be safe in all other ways. This is because I keep different versions of files in my dotbot repository, and several YAML files to install different versions, and would like to switch between them on the fly.

I have a further feature request: Possibility to set the default behaviour so that one can limit the verbosity of the YAML file; i.e. set globally `force: true` or the like.

Thanks for your consideration.

**Comment by anishathalye** [comment]
Hmm, that's a good point.

Do you think we could have an option like `relink: true` for overwriting symlinks but not deleting files (so no data loss)? And then the `force: true` could stay how it is -- it'll remove the file (or link) if necessary. How does this sound?


Default behavior is a little bit more tricky. I definitely agree with you that it'll be a great thing to have, I'm just not sure what's the right interface. Should it go in the config file itself? With the current YAML/JSON format, I'm not sure where that would go. Should it be a command line option? I feel like that might get messy.

Do you have any ideas?

**Comment by Ploppz** [comment]
`relink` is a good idea. A suggestion for setting defaults is to put this in the same .yaml file as everything else:
```
- default:
     force: true
```

**Comment by anishathalye** [comment]
`relink` should be doable.

Currently, the YAML file is declarative.

Adding something like this seems out of place:

```yaml
- default:
  force: true
```

Because the "default" is not another action to be executed.

Maybe something like this could be better:

```yaml
defaults:
  link:
    force: true
  shell:
    stdout: true
config:
  - link:
      ~/.vimrc: vimrc
  - shell:
    - echo hi
```

But I'm not super happy with that either.

**Comment by Ploppz** [comment]
Yes that works. One more suggestion:
```yaml
- link:
    default:
        force: true
    ~/.vimrc: vimrc
```
Or maybe that has the potential to crash with a file "default" - maybe `- default` instead. I don't know so much about yaml. Well that's a suggestions and I'll leave it up to you to decide what you want to do :)

**Comment by anishathalye** [comment]
Yeah, you're right, that has the potential to clash with the file `default`. In that context, `- default` is not actually valid YAML.

**Comment by anishathalye** [comment]
`relink` functionality implemented! (3725d21)

The default configuration syntax might have to wait until Dotbot 2.0 (unless someone comes up with a nice way to integrate it into the current design).

**Comment by Ploppz** [comment]
Hm, it says that it only overrides *broken* symbolic links. Unless I'm misunderstanding something: What I would need is to override any symbolic link, because my case may be like this:
```
. (dotfiles directory)
├── dircolors-green
└── dircolors-plumb
```
And then I would have `green.yaml` and `plumb.yaml` which would link `.config/dircolors` to `dotfiles/dircolors-green` and `dotfiles/dircolors-plumb` respectively.

I would say that this behaviour is not destructive, as a symbolic link in itself does not hold a lot of information - there shouldn't be any consequences in most cases.

**Comment by anishathalye** [comment]
Perhaps my commit message wasn't the best. It does overwrite broken *and incorrect* symbolic links, behaving the way you described.

**Comment by Ploppz** [comment]
Ah yes indeed, I think I just misunderstood words. Thanks for implementing it. And sorry for this late reply - this is the first time I actually come back to my dotfiles for a while.

I have a problem: I pulled the latest version; my `HEAD` is now at `commit 53c26ba: "Clean up code"`. I have a lot of links defined like this:
```
    ~/.config/theme:
        path: theme-green/
        relink: true
```
But I still get the `Incorrect link` error on all of them. I'm wondering if I didn't update dotbot correctly. I went into the dotbot directory and wrote `git pull origin master`.

**Comment by anishathalye** [comment]
What's happening is that the Dotbot install script fetches the version of Dotbot that's committed in git. To update to a newer version of Dotbot, run:

```bash
git submodule update --init --remote dotbot && git add dotbot
```

After this, running `./install` should work just fine (and then once you check, you can commit the change to your dotfiles).

**Comment by Ploppz** [comment]
@anishathalye How is it going with default configuration and Dotbot 2.0?

**Comment by anishathalye** [comment]
Haven't started on it yet.

**Comment by Ploppz** [comment]
Alright. No hurries.
