### ISSUE TITLE
Wheel distribution on pypi doesn't pass the tests since it's missing some files under the tests/ directory

### ISSUE THREAD

**Issue by ludat** [anishathalye/dotbot#350]
I'm packaging this project for nixos and looks like downloading from pypi doesn't work since there are some files that are missing.

Specifically `tests/conftest.py`, I'm guessing while uploading it's only pushing `test_*.py` files

**Comment by anishathalye** [comment]
I see that those files are missing, but why does this prevent dotbot from downloading/working? I'm able to download from PyPI and run Dotbot on my machine. Something special going on with nixos?

**Comment by anishathalye** [comment]
I tried this:

```diff
diff --git i/setup.py w/setup.py
index 06bc7bf..c7f63b6 100644
--- i/setup.py
+++ w/setup.py
@@ -48,7 +48,7 @@ setup(
         "Topic :: Utilities",
     ],
     keywords="dotfiles",
-    packages=find_packages(),
+    packages=find_packages(exclude=["tests"]),
     setup_requires=[
         "setuptools>=38.6.0",
         "wheel>=0.31.0",
```

But it didn't seem to work. I don't have time to dig deeper at this instant, but will take a closer look probably in a couple days.

**Comment by ludat** [comment]
I'm trying to package this project for nixos (https://github.com/NixOS/nixpkgs/pull/264729/files).

I ended up downloading the package from github instead of pypi so everything works

If you feel like it you can close this as won't fix

**Comment by anishathalye** [comment]
Let's leave the issue open, I'd like to fix when I have some free time (or someone submits a PR).

**Comment by anishathalye** [comment]
I think this is fixed, see related discussion https://github.com/anishathalye/dotbot/issues/365.

Please re-open this issue if anything is still broken.
