### ISSUE TITLE
Duplicate directives when custom plugins import builtins

### ISSUE THREAD

**Issue by aananiadis** [anishathalye/dotbot#357]
If a plugin is added that imports `dotbot.plugins` (such as [dotbot-if](https://github.com/wonderbeyond/dotbot-if/blob/28b2fc6042eff75b4190cccf70357e4b8346cf76/if.py#L8)) the built-in plugins will be included multiple times and then duplicate execution of the directives.

Example (tested with dotbot version 1.20.1):
With [dotbot-if](https://github.com/wonderbeyond/dotbot-if/tree/main) in `dotbot-plugins` directory, and the following config:
```yaml
- shell:
    - description: Demo shell
      command: echo "Should run once"
```

```
$ dotbot/bin/dotbot -c test.conf.yaml -p dotbot-plugins/dotbot-if/if.py
Demo shell [echo "Should run once"]
All commands have been executed
Demo shell [echo "Should run once"]
All commands have been executed

==> All tasks executed successfully
```

Perhaps the Dispatcher should dedupe the plugin list, or plugin module loading could ignore builtins?

**Comment by anishathalye** [comment]
Thank you for reporting this. Fixed in https://github.com/anishathalye/dotbot/commit/cef40c902ef0f52f484153413142b5154bbc5e99.
