### ISSUE TITLE
env if else

### ISSUE THREAD

**Issue by maxclax** [anishathalye/dotbot#368]
```
   ~/.config/nvim:
      path: ./config/nvim/lazyvim
      if: '[ "$NVIM_TYPE" = "lazyvim" ]'
    ~/.config/nvim:
      path: ./config/nvim/kickstart
      if: '[ "$NVIM_TYPE" = "kickstart" ]'
```

Can I use it? I have tried but any result. I have use also

```
    ~/.config/nvim:
      path: ./config/nvim/$NVIM_TYPE
```

But with it I have error like 

`Nonexistent source ~/.config/nvim -> config/nvim/lazyvim` and with full path that also  texted me about Nonexistent

**Comment by anishathalye** [comment]
The first version won't work (it's a YAML dict, and can't have duplicate keys, so one entry gets clobbered).

The second option should work. To test it, I tried adding the following to my `install.conf.yaml` file:

```yaml
    ~/.config/nvim:
      path: ./config/nvim/$NVIM_TYPE
```

I also created the file, `echo test > ./config/nvim/lazyvim`, and then:

```bash
export NVIM_TYPE=lazyvim
./install
```

And I got the following output:

```
...
Creating link ~/.config/nvim -> /Users/anish/src/dotfiles/config/nvim/lazyvim
...
```

Could you say more about the error message you are seeing / paste it verbatim here?

**Comment by maxclax** [comment]
> The first version won't work (it's a YAML dict, and can't have duplicate keys, so one entry gets clobbered).
> 
> The second option should work. To test it, I tried adding the following to my `install.conf.yaml` file:
> 
> ```yaml
>     ~/.config/nvim:
>       path: ./config/nvim/$NVIM_TYPE
> ```
> 
> I also created the file, `echo test > ./config/nvim/lazyvim`, and then:
> 
> ```shell
> export NVIM_TYPE=lazyvim
> ./install
> ```
> 
> And I got the following output:
> 
> ```
> ...
> Creating link ~/.config/nvim -> /Users/anish/src/dotfiles/config/nvim/lazyvim
> ...
> ```
> 
> Could you say more about the error message you are seeing / paste it verbatim here?

That interesting and logical to work but in my case I don't understand why I have this error because with VAR in path that like in installing process script looking not in correct direction and I have error  `Nonexistent source ~/.config/nvim -> config/nvim/lazyvim` but when I tried use full path to my vim `/Volume/dev/dotfiles/config/nvim/$NVIM_TYPE` I have also same error but with full path but in same time I have correct path. Maybe some encoding for `/`

**Comment by maxclax** [comment]
And all work well when I use without VAR just /Volume/dev/dotfiles/config/nvim/lazyvim or ./config/nvim/lazyvim

**Comment by anishathalye** [comment]
That is perplexing. Could you share: OS version, Dotbot version, exact snippet of the config that you expect to work, and the verbatim error message you get? Could you also share info about your file system setup (are there any symlinks in the path to the file? Anything else unusual?), and any other information that might be helpful for debugging?

**Comment by maxclax** [comment]
This variant works well without $VAR
<img width="1420" alt="Screenshot 2024-11-14 at 11 34 57 AM" src="https://github.com/user-attachments/assets/dcd9c6d9-f9a7-4e67-aaa3-7adcf93b0a0a">

**Comment by maxclax** [comment]
Ohhh! That my bad in my .env was with commenting and that was effected. Sorry

`NVIM_TYPE=lazyvim # lazyvim or kickstart`

**Comment by anishathalye** [comment]
Glad you got it sorted out!
