### ISSUE TITLE
Suggestion for new plugin

### ISSUE THREAD

**Issue by msarti** [anishathalye/dotbot#369]
[sops plugin](https://github.com/elogiclab/dotbot-sops)  allows you to decrypt files encrypted with sops before they are processed. It is useful in case there are sensitive files in the dotfiles that need to be committed in encrypted form.

Having developed it for my own use I am reporting it to share with the community.

**Comment by anishathalye** [comment]
Cool! Could you add it to the [wiki](https://github.com/anishathalye/dotbot/wiki/Plugins)?
