### ISSUE TITLE
Test using both python2 and python3

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/dotbot#40]
Dotbot, at least with `1.x`, will maintain compatibility with both Python 2 and Python 3.
This can sometimes be painful to do, and sometimes, it can be error-prone. In the past, there have been bugs with cross-version compatibility.

It would be good to modify the testing code so that tests are run with both Python 2 and Python 3. Currently, it only tests with Python 2.

**Comment by PacketPerception** [comment]
While the bash testing is elegant and simple, would it be more beneficial to move to a testing suite that could be run in something like Travis CI? Thinking python unittest test cases running within temporary directories. Tests would run a lot faster as well.

**Comment by anishathalye** [comment]
Yeah, it would be awesome if we could move to a testing suite that could be run in Travis CI.

I'm not sure how unit test cases running within temporary directories would work - I wouldn't want a broken test case or broken code to screw up a machine. That's why I went with the whole VM thing (that's super duper slow...).

I've spent a tiny amount of time looking into file system mocking in Python, but I haven't read enough about it to figure out if it's a good choice for what we're doing.

Figuring out how to make tests run faster (in the VM or outside the VM) would be awesome.

**Comment by anishathalye** [comment]
It looks like this might be a reasonable way of testing with multiple Python versions: http://redsymbol.net/articles/env-and-python-scripts-version/

**Comment by PacketPerception** [comment]
When testing with Travis-CI, this is a non-issue, check out my travis configuration for one of my projects: https://github.com/PacketPerception/pychievements/blob/master/.travis.yml

That results like so: https://travis-ci.org/PacketPerception/pychievements and even generates coverage reports via coveralls, https://coveralls.io/builds/2864248

Here I'm using nose which is just a super simple way of running unittest.TestCase tests. I'd be more than happy to try write one up as an example to see if it would work out. 

For testing locally on your own machine, I highly recommend pyenv for managing your python versions, then using tox to automatically run tests against multiple versions. See http://tbb.co/using-tox-and-pyenv-for-testing-and-development/ for an example

**Comment by anishathalye** [comment]
Yeah, good point about FS modification and bugs not being an issue with Travis-CI. Coveralls is nice too.

If it wouldn't be too much work, it would be nice to see what a test case would look like.

And thanks for the link about pyenv/tox. I didn't know too much about good ways to do that.

**Comment by PacketPerception** [comment]
Had a slow evening... I implemented the clean and config tests really quick just as a simple example. Check out the README in the test directory. The tests I did write are passing on Python 2.6, 2.7, 3.2, 3.3, and 3.4.

**Comment by PacketPerception** [comment]
Oh, and btw, running the tests (on all versions of python) takes 3 seconds ;p

**Comment by PacketPerception** [comment]
Added a travis-ci configuration, so it auto-runs the tests - https://travis-ci.org/PacketPerception/dotbot

**Comment by PacketPerception** [comment]
Got coveralls working and reimplemented all of the old tests. https://coveralls.io/r/PacketPerception/dotbot

At this point, I say feel free to grab/pull these in if you want. The dotbot README.md would have to be updated with links to Travis-CI/Coveralls, assuming you setup an account to run them. Other than that, this is now a full conversion of the tests using tox/pyenv. Takes 3.3 seconds to run the entire suite against 5 versions of python.

**Comment by anishathalye** [comment]
Finally done in 5babc8f562f9ba1ad3e78b5ec6906aa33d17c0a9!
