### ISSUE TITLE
A question about linking

### ISSUE THREAD

**Issue by bodypheo** [anishathalye/dotbot#47]
Hello,
I am looking for a way to easily track my dotfiles and I  am considering using dotbot. But I would like to know if it has a feature, important to me. In the linking step is it possible to make backup of the existing files? Imaging I change distro or software version and when I deploy my dotfile something happens. I would  like to be able to vimdiff the previous (default) file and see what can be happening.
I have been reading the link section but I don't know if this is possible.

Thank you very much.

**Comment by anishathalye** [comment]
Dotbot is safe in that it does not overwrite files. Dotbot by default won't overwrite files, it'll just skip those and warn you about the ones it skipped. If you want, you can set an option to overwrite files.

So if there are existing files or whatever, there won't be any data loss.

A related topic, automatic backups, was discussed in #12 and #36. I don't think it's going to be a feature in Dotbot 1.x. It seems a bit odd to pop up a vimdiff window when installing your dotfiles - that should probably happen outside that flow.

**Comment by bodypheo** [comment]
Hello, thanks for your answer. I was thinking more in the flow of backup existing files, deploy your dotfiles and if there is any problem I would manually check it the files. But it is ok to me if dont overwrite and warn me about it.
Thanks.
