### ISSUE TITLE
Invalid links not cleaned.

### ISSUE THREAD

**Issue by synthecypher** [anishathalye/dotbot#48]
![image](https://cloud.githubusercontent.com/assets/1833542/9292982/0c31bd62-440e-11e5-8348-2531c25f15c5.png)

**Comment by anishathalye** [comment]
Hmm, where are those invalid links currently pointing? As the [documentation](https://github.com/anishathalye/dotbot#clean) states, only dead links that point to the dotfiles directory are removed (for safety).

For example, if you move your dotfiles directory, it won't clean those links.

In this case, do you want something more like the [relink](https://github.com/anishathalye/dotbot#format) setting? (the configuration for that is a little verbose right now; that should be improved in a future version of Dotbot)

**Comment by anishathalye** [comment]
I'm going to close this now; feel free to reopen if there is anything else.
