### ISSUE TITLE
Shell commands run after link commands?

### ISSUE THREAD

**Issue by Brottweiler** [anishathalye/dotbot#51]
Let's say I would set up my dotfiles repo on another computer, from the config and console output it sounds like it links the files first, then runs the shell commands which would create directories.

It can't link when there's no folder, right? So shouldn't the folders be created first? Otherwise you'd just run the script twice...

Also, I had some additional questions:

- The script doesn't seem to like this `- [mkdir -p ~/.local/{bin,share}, Creating local bin and share dirs]`

It throws this because it thinks the `{` is the "end of line" character which should be `]`
```
Could not read config file:
  while parsing a flow sequence
    in "install.conf.yaml", line 26, column 5
  expected ',' or ']', but got '{'
    in "install.conf.yaml", line 26, column 24
```

Other than that, I just setup my repo using dotbot, and it is awesome so far! Was just a pain in the butt to create folders, move files, write it in the config, run the config... :stuck_out_tongue: 

- How does dotbot handle existing files? For example, when you have a newly setup OS, `.bashrc` will probably exist already, and dotbot would fail to symlink because it exists.

**Comment by anishathalye** [comment]
It runs things in the order specified. So you could have `shell` commands first, then `link` commands, then more `shell` commands if you want. Like [this](https://github.com/ismay/dotfiles/blob/6fa79a9d15eaf601408c7226f83859b1c28992b3/install.conf.yaml), for example.

As for the funny characters like `{` - you can just put the entire string in quotes. You can always check your YAML syntax online using something like [this](http://yamltojson.com/).

I'm glad Dotbot is working out for you! It's a bit of work to set it up for the first time, but now, when you switch machines and stuff, you'll be up and running in no time.

By default, Dotbot will *not* overwrite existing files - it's safe. It'll show you a warning message and you can delete the existing file yourself if you want to. Alternatively, you could use the `relink` or `force` [options](https://github.com/anishathalye/dotbot#format).

**Comment by Brottweiler** [comment]
About the order, wouldn't it make sense to have the shell commands first? Atleast the commands that create directories. The shell command to update the dotbot submodule is probably at the end by design. I see now that you can put shell, then link, then shell again, so you can have the folders created first, then links, then the submodule update.

It worked for me by removing the brackets (`[`), but then it wouldn't print out as fancy as before. 
Do you mean like this `- ['mkdir -p ~/.local/bin', Creating local bin dir]`?

First I was using a script I found on some website talking about dotfiles, but this is way more robust. What that script would do was to *move* existing dotfiles to a `dotfiles_old` directory, then it would link. This folder would be a backup folder, but I'm not saying dotbot should be like that, I guess it can be messy since you end up with a folder with a bunch of old crap you don't use.

**Comment by anishathalye** [comment]
Yeah, you can run whatever commands in whatever order you want. You could omit shell commands entirely, you could have ten different sections of shell commands intertwined with other stuff, etc.

Yeah, I meant like `- ["mkdir -p ~/.local/bin", Creating local bin dir]`. It's just an array containing two strings. Sometimes, it's okay to omit the quotes, but other times, it's necessary (if you're using certain special characters in the string).

Backups have been discussed before (see #12 and #36), there will probably be a feature related to this in Dotbot 2.0.

**Comment by anishathalye** [comment]
I'm going to close this now; if you still have a question, feel free to re-open.
