### ISSUE TITLE
(enhancement) installed: program_in_path

### ISSUE THREAD

**Issue by sharethewisdom** [anishathalye/dotbot#52]
hi, 
I'm not sure if you'd want to consider a new simple feature. Dotbot is fine (great!) the way it is, really.

But suppose you've got an extensive list of entries under `- link:`, and you'd want to run the `install` on a fresh, minimal distro. Wouldn't it be useful to check if a program is installed first? This check is also partly included in my amateur configs and I'm working to make them more modular and avoid broken functions and aliases. I'd like to link only the configs I need, no more. EDIT: specifying another config file in `install` is obviously the simple solution.

Maybe we could have dotbot skip the creation of directories and symlinks based of the condition that if an `installed: $1` setting was specified in a *list* entry and `which $1 &>/dev/null` (or similar) evaluated false. A separate `cleanuninstalled` command could be used to also clean symlinks (that point to the dotfiles directory and aren't broken), when the specified program is not in $PATH anymore. And lastly, `bin/dotbot` could be given an option to ignore this feature.

Note that I don't mind branching out and removing entries from install.conf.yaml, but dotfiles aren't like typical repo's, and changes in this branch might not get merged into master soon. Not without much pain at least. 

anyway, thank you for this wonderful tool, I love the installer and the submodule approach.

**Comment by anishathalye** [comment]
I'm glad you've found the tool to be useful! :smile:

Hmm, this is an interesting idea. It shouldn't be too hard to implement.

What's the harm with setting up symlinks for programs that are not installed? Like if you don't have `vim` installed, but you link up `~/.vimrc` anyways, is that bad? If someone ends up installing the program later, then they'd need to re-run the installer.

**Comment by sharethewisdom** [comment]
You're right, though one reason I can think of is that it feels *less intimidating* when `HOME` is clean, and when configuration files just for installed programs are to be found in `XDG-CONFIG-HOME`. 

I'm introducing someone to a basic GUI-less Arch linux system who will be using the same logon. The idea is that we learn (and get more used to) git workflow by adding tools and their configs one at a time, while I'd like to prepare and comment configs on a fully tooled-up machine. This sounds specific, I know. Again I have no real need for this feature, but I like to write down ideas as they come.

ps. you might know [Rifle](https://github.com/hut/ranger/blob/master/ranger/config/rifle.conf) which has a modular approach, so that ranger only lists relevant choices when using the `:run` command.

**Comment by sharethewisdom** [comment]
Today, I stumbled upon this:
>  [Dots](https://github.com/EvanPurkhiser/dots) offers the following features:
>  
>   * **Configuration groups**  
>     When installing your dotfiles onto a new machine, `dots` offers you the
>     ability to select a specific 'group' of dotfiles that you would like to have
>     installed into that environment. By organizing your dotfiles into logical
>     groups (such as 'machine' groups) it's possible to only install the dotfiles
>     that are required by that environment.

Also, I didn't notice [QiangF's suggestion](https://github.com/anishathalye/dotbot/issues/49) before: to *organise the .install.conf.yaml by applications* [...] and *install or export dotfiles by application names or user defined category*. Maybe, if `program_in_path` is found, a group of dotfiles would be installed.

**Comment by anishathalye** [comment]
Hmm... given that it's fairly straightforward to achieve something similar to this (see #11), I think it's better to avoid additional complexity in Dotbot.
