### ISSUE TITLE
Print error when command isn't successfully executed

### ISSUE THREAD

**Issue by lc-guy** [anishathalye/dotbot#54]
Currently, this is what happens when using ./install : 
```
Installing submodules [git submodule update --init --recursive]
Installing vim plugins [vim +PluginInstall +qall]
Installing zsh bundles [source '~/.config/zsh/.zshrc']
Command [source '~/.config/zsh/.zshrc'] failed
Some commands were not successfully executed

==> Some tasks were not executed successfully
```

when trying out the command itself, no error message appears and the exit code is 0. It would be nice to know why a command fails.

**Comment by anishathalye** [comment]
It's suppressed on purpose. If you want to see a command's stderr output, you can [explicitly allow it](https://github.com/anishathalye/dotbot#example-1).

**Comment by anishathalye** [comment]
Also, it looks like you are sourcing your `.zshrc` in subshells. I don't think that'll do what you want it to do.

**Comment by lc-guy** [comment]
Ah, yeah, sorry.

The reason I'm sourcing .zshrc is because antigen (zsh bundle manager) downloads/installs bundles upon opening a new zsh session / loading zshrc. I figured this is the best way to do it immediately.

**Comment by lc-guy** [comment]
yea I just realised how I fucked up, sorry.

Closing this, sorry for bothering you.

**Comment by anishathalye** [comment]
No worries!

If you do want to source that file when you install, you could add the source command to the end of the `install` script.

**Comment by lc-guy** [comment]
I actually managed to work around it by using "zsh -c '~/.config/.zshrc'" as the command.
