### ISSUE TITLE
Create directory if not present

### ISSUE THREAD

**Issue by jasonszhao** [anishathalye/dotbot#55]
I got a `Linking failed` error because I attempted put a link at `~/.vim/plugins.vim`, but the `~/.vim` directory didn't exist. 

**Tested Workaround**: `mkdir ~/.vim`

**Comment by anishathalye** [comment]
See the [path](https://github.com/anishathalye/dotbot#format) option

**Comment by jasonszhao** [comment]
Thank you. I see. It would be nice there was an option to set the option for all of them.

**Comment by anishathalye** [comment]
Yup, the plan is to do that eventually. See discussion in #34.
