### ISSUE TITLE
Support ANSI sequences under windows

### ISSUE THREAD

**Issue by brandto** [anishathalye/dotbot#59]
dotbot works even under windows "as is" if you are able to create symlinks. So using python3 and having the rights to create symlinks you'll be able to use this great tool.

But as "cmd.exe" doesn't support ANSI you will not get colored output. Should be easy to fix using "colorama".

**Comment by anishathalye** [comment]
Hmm I haven't used it Windows. Is the output just not colored, or does it have funny escape sequences in it?

Also, I don't want to add an external dependency. Hopefully, it shouldn't be hard to reimplement the functionality.

**Comment by anishathalye** [comment]
I haven't used Dotbot on Windows before. How does this currently look?

I would prefer to avoid adding more external dependencies for something like this.

**Comment by brandto** [comment]
As a matter of fact you'll get the 'ugly escape sequences'.

**Comment by brandto** [comment]
Would it be ok for you if we just add a single file?! As an example https://github.com/pycontribs/tendo/blob/master/tendo/ansiterm.py could be used.

Another possibility: Check for installed colorama (or ansiterm) on the machine (if running under windows). If found something useable: use it. If not: Use "empty" ANSI sequences.

**Comment by anishathalye** [comment]
Hmm I'm not sure if I want to include a couple hundred lines of code for prettier colors on Windows (also, the colors aren't _that_ useful).

Stripping escape sequences on Windows seems reasonable, though.
