### ISSUE TITLE
Enable Relink with Command Line Option

### ISSUE THREAD

**Issue by cmcginty** [anishathalye/dotbot#61]
I see that the linker.py supports a relink option to update a symbolic link that is not pointing to the correct target. Could you provide a global way to enable relinking of every link in the dotbot config?

This would support a few edges cases when you know you want to let dotbot clobber valid symbolic links.

**Comment by anishathalye** [comment]
Dotbot 2.0 will support default options, so the config file could have `force: true` in a single place, and that'll apply to everything to be linked. See #35 

I don't think it's worth special-casing `relink` and having a command-line option for it.

**Comment by cmcginty** [comment]
That works too. Thanks.
