### ISSUE TITLE
Extra slash in link target when linking a directory

### ISSUE THREAD

**Issue by KibaFox** [anishathalye/dotbot#64]
I setup my dotbot config to include a trailing slash at the source directory.

Here's a snippet from my yaml config file:

```yaml
- link:
    ~/.config/fish: fish/
    ~/.config/i3: i3/
    ~/.config/nvim: nvim/
```
However, after running the script, the links point to the directory with an extra slash.

Here's a snippet of the output from running `ls -l ~/.config`:

```
fish -> /home/user/lib/dotfiles/fish//
i3 -> /home/user/lib/dotfiles/i3//
nvim -> /home/user/lib/dotfiles/nvim//
```

This isn't breaking anything, but it'd be nice to not have extra slashes appear.

One workaround is to not put the trailing slash into the config file, but I like being able to see that I'm linking a directory at a glance from the config file.

**Comment by anishathalye** [comment]
(tagging as `enhancement` because the bug is more of an aesthetics thing. doesn't make the most sense but whatever...)

Huh, weird...

I do the same thing with my install config, with the trailing slash (see [here](https://github.com/anishathalye/dotfiles/blob/97913112ffaecea8957a03d82415033b9fcfd0a0/.install.conf.yaml)).

I don't currently have access to all my testing machines, but on Linux (Ubuntu 14.04) using Python 2.7.6 and dotbot@5babc8f56, it seems to work just fine, not adding the extra trailing slash.

Could you provide more details about your system configuration?

**Comment by KibaFox** [comment]
Hm.  That is weird that you're not seeing it.

Here's what I'm currently running:

  * NixOS 15.09
  * Python 2.7.10
  * Dotbot 5babc8f

**Comment by anishathalye** [comment]
Huh. I can't reproduce it on my system, so it's pretty much impossible for me to debug this until I can do that...

Maybe it has something to do with NixOS or your Python installation?

If you want to start looking into it, feel free.

**Comment by KibaFox** [comment]
> Maybe it has something to do with NixOS or your Python installation?

Quite possible.  I'll start looking into it and see if I can find a solution.

**Comment by anishathalye** [comment]
Okay, sounds good. Seems like a pretty strange issue, I'd be interested to know what's going on. Good luck! :smile:

**Comment by KibaFox** [comment]
Okay.  I did a fresh install of Ubuntu (on VirtualBox) and I couldn't reproduce the issue.  But here's the interesting part, I did a fresh install of NixOS (on VirtualBox) and I couldn't reproduce the issue either.

I'm going to assume it's a fluke, so I'm closing this issue.  If it comes back up I'll take a closer look into what's causing it before I reopen this.

Sorry to bug you (no pun intended).  Thank you for the support!

**Comment by anishathalye** [comment]
Wow, that's really strange. Well, I'm glad it all worked out in the end!

**Comment by KibaFox** [comment]
Me too.

**Comment by hupfdule** [comment]
Hi there. I am seeing this problem also.
I have the following in my `.install.conf.yml`:

    link:
      /tmp/foo: bar/
      /tmp/foo2: bar2

When calling `.install` it prints:

    Creating link /tmp/foo -> /home/hupfdule/.dotfiles/bar/
    Creating link /tmp/foo2 -> /home/hupfdule/.dotfiles/bar2

And this is the result:

    $ /bin/ls -lhd /tmp/foo*                                                                                              
    lrwxrwxrwx 1 hupfdule hupfdule 27 Dez  5 12:31 /tmp/foo -> /home/hupfdule/.dotfiles/bar/
    lrwxrwxrwx 1 hupfdule hupfdule 27 Dez  5 12:31 /tmp/foo2 -> /home/hupfdule/.dotfiles/bar2

So there obviously is a difference. If it is a problem or not: I don't know.

However, this is a problem:

    link:
      /tmp/foo: bar/
      /tmp/foo2/: bar2/

resulting in:

    Creating link /tmp/foo -> /home/hupfdule/.dotfiles/bar/
    Linking failed /tmp/foo2/ -> /home/hupfdule/.dotfiles/bar2/

It actually conforms with the behaviour of `ln -s` where

    ln -s bar foo/ 

also leads to an error `target 'foo/' is not a directory: No such file or directory`. But it would be nice if dotbot would support it.

**Comment by anishathalye** [comment]
One thing we could do is strip a trailing `/` in the target, and this would make `/tmp/foo2/: bar2/` work. But I think the current behavior is better. Matching `ln`'s behavior is good, and I think it's good to throw an error rather than silently removing the trailing `/`
