### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by Azd325** [anishathalye/dotbot#66]
Hey :)

In your latest commit https://github.com/anishathalye/dotbot/commit/47ad7f4d3b69315e25ae96099fe73b4d9cd7666e you was adding a print and this breaks the execution on python 3.

It should be removed or improved that it runs on both versions.
https://github.com/anishathalye/dotbot/blob/master/dotbot/config.py#L14

**Comment by bchretien** [comment]
On a sidenote, the Travis CI integration suggested in #40 would help catch that kind of issues.

**Comment by anishathalye** [comment]
Oh dear, sorry about that! I ran the tests after the change, but I forgot to run with `--version 3.x` as well.

Will fix in a couple minutes (pushing after tests finish :stuck_out_tongue:)

Yeah @bchretien, you're right. Looks like it's possible: http://www.lewuathe.com/blog/2015/01/25/vagrant-in-travisci/

**Comment by anishathalye** [comment]
Ok, fixed.
