### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/dotbot#67]
So things like #66 don't happen.

Looks like it's possible: http://www.lewuathe.com/blog/2015/01/25/vagrant-in-travisci/

CC @bchretien

**Comment by bchretien** [comment]
cc @PacketPerception

Nice! Just a quick note: the link you posted presents an approach that depends on `sudo`, thus preventing the use of the [new container-based infrastructure](https://docs.travis-ci.com/user/workers/container-based-infrastructure/). This is not a requirement, but with it builds start faster (and availability is probably improved). It may not be possible yet though (apt packages need to be [vetted](https://github.com/travis-ci/apt-package-whitelist) etc.). Moreover, the person who wrote that post [no longer uses that](https://github.com/Lewuathe/storm-cookbook/commit/53b5b1c62b2a3480bb01b3faef236f00cacdfb7e) (nor Vagrant it seems, it's hard to tell). Then again, I haven't ported all my projects to the new infrastructure either for the exact same reasons, and it works just fine.

To investigate Travis CI, you should consider making a new branch (e.g. `travis`), and enable it on Travis (see [this](https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches)). That way you don't pollute `master`, and you can just rebase the branch on `master` once things work as expected.

**Comment by bchretien** [comment]
Actually, it may be even better to run the tests without Vagrant completely, since there is no risk of breaking the system. In that case, things are much easier, [this guide](https://docs.travis-ci.com/user/languages/python) shows the possibilities for Python projects.

**Comment by anishathalye** [comment]
Fixed in #68.
