### ISSUE TITLE
Relative symlinks

### ISSUE THREAD

**Issue by harkabeeparolus** [anishathalye/dotbot#70]
Hi,

Would it be possible to let dotbot figure out relative instead of absolute symlinks?

Instead of how it looks today:

.zshrc -> /Users/traal/dotfiles/zshrc

It would be much cleaner to have this:

.zshrc -> dotfiles/zshrc

This also makes the directory structure more reliable and portable.

Cheers,

Fredrik Mellström

**Comment by anishathalye** [comment]
Hi Fredrik,

Dotbot already supports relative links like that. For an example, see my [install.conf.yaml](https://github.com/anishathalye/dotfiles/blob/97913112ffaecea8957a03d82415033b9fcfd0a0/.install.conf.yaml).

**Comment by harkabeeparolus** [comment]
Hi @anishathalye, thanks for responding.

What specifically makes dotbot generate relative symlinks instead of absolute? I see no difference between syntax or options in your config file and mine.

If it matters, I'm running dotbot cloned from github, on the latest Mac OSX 10.11.3, with homebrew. I do have a bunch of homebrew utilities installed, but I don't believe I'm overriding any important system binaries such as "python".

As far as I can tell, dotbot simply expands ~ to /Users/traal no matter what I do.

I even tried changing the wrapper script so I'm running the dotbot binary in my $HOME with a relative path for the "-d" flag.  Didn't work either.

Any ideas?

Cheers,

Fredrik Mellström

**Comment by anishathalye** [comment]
Oh, okay, I think I was misunderstanding what you wanted to do.

Is this correct: if you have your dotfiles in `~/src/dotfiles` and you have a file in there called `vimrc` that you want to link to `~/vimrc`, you want a link like `~/vimrc -> src/dotfiles` instead of `/Users/$HOME/src/dotfiles`, and you want Dotbot to automatically figure out what that relative path should be?

I'm not sure why this kind of relative link is necessary; I don't see how it is more reliable and portable. Your `$HOME` is going to expand to the correct thing on each machine you use, so links will work wherever you run this.

**Comment by harkabeeparolus** [comment]
Yes, that is correct.  I would like to have the option to change `.zshrc -> /Users/traal/dotfiles/zshrc` to `.zshrc -> dotfiles/zshrc`, and so on.

As to why, relative links are not strictly **necessary** on many systems, especially for single-user systems.

However, sometimes they are.  For instance, I work at a university with large, multi-user unix systems. I can have my personal home directory from the NFS file server mounted on different paths, on different hardware architectures and computers. If I log in to several different systems where the same home directory is mounted on a different $HOME path, I will have to re-run dotfiles on each login.  Actually that's not even possible, unless I would wrap my entire login session inside a script that re-runs dotfiles to "fix" all the symlinks before launching my login shell. And even then, I could not be logged in to more than one system at a time.

Basically, what is evaluated as $HOME at the time of running dotfiles is not necessarily the exact same absolute path that I'm always going to have my home directory mounted on. Especially if your home directory is located on a file server. As it is, I can run dotfiles reliably on a laptop, but not necessarily on university Unix computers without resorting to ugly hacks.

Moreover, if I make a backup .tar.gz archive of my $HOME directory, and later uncompress my backup to a working copy somewhere else, I would prefer not to have broken symlinks (until the next time I manage to get dotfiles configured so I can re-run the script).

Those are just the examples I came up with now off the top of my head. I'm sure there are other situations where relative symlinks could be more robust and/or useful.

Also, I'm sure there are situations where you **do** want absolute symlinks. If you would consider this feature at all, it should probably be user configurable.

//Fredrik

**Comment by harkabeeparolus** [comment]
By the way, @anishathalye, a bit of Googling turned up this very simple and extremely reliable way of generating relative symlinks with python 2.6 or better:

http://stackoverflow.com/a/7305217

I noticed that you're already using os.path in your code, so coding it should be a very simple addition.

Cheers,
Fredrik

**Comment by anishathalye** [comment]
Okay, that seems reasonable. Does it make sense to add an option like `relative: true` to specify that you want a relative link? This should be pretty straightforward to code. It might be slightly annoying to use for now (it would need to be specified for every link target), but with default options in Dotbot 2.0, it should get better.

**Comment by harkabeeparolus** [comment]
That sounds like a good option for now, @anishathalye.  Thanks for listening to my feedback, I really appreciate it.  :-)

**Comment by anishathalye** [comment]
How does this look: https://github.com/anishathalye/dotbot/commit/daf8d82e02c2bcc476932790fa25076631c4c312 ?

It's on the develop branch, not merged into master yet. I just wanted to make sure that this was doing the right thing / what you wanted.

Once I have the thumbs-up from you, I'll go ahead and merge it.

**Comment by harkabeeparolus** [comment]
@anishathalye, I checked out the develop branch and tested the basics. Works perfectly!

Big thumbs-up from me!  :-)

**Comment by anishathalye** [comment]
Awesome! Merged.

**Comment by sjthespian** [comment]
This update seems to have an issue with subdirectories. If I create ~/.ssh/conf.d/foo.conf for example, dotbot will remove and relink it every time I run the script if I set relative to true (or at least it does on my Mac). 

```
- defaults:
    link:
      relink: true
      relative: true

- link:
    ~/.ssh/conf.d/foo.conf:     ssh/conf.d/foo.conf
```
