### ISSUE TITLE
Add note about how to use multiple link targets to README

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/dotbot#72]
See #11

**Comment by anishathalye** [comment]
Actually, maybe it's better to keep this out of the readme. That document is long enough as it is. Maybe we'll make a wiki or something at some point.

**Comment by motlin** [comment]
Friendly reminder to please add this to the wiki!

**Comment by anishathalye** [comment]
This is covered here: https://github.com/anishathalye/dotbot/wiki/Tips-and-Tricks#how-can-i-have-different-groups-of-tasks-for-different-hosts-with-different-configurations

**Comment by anishathalye** [comment]
Sure, could you please make the edit directly?
