### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/dotbot#73]
cc @MaikuMori

**Comment by anishathalye** [comment]
[Moving discussion here from #35. @darksider3]

Uhh, I haven't thought too much about this / haven't had too much time. If you want, feel free to start thinking about this and replying here with your thoughts. Or if you want, start hacking on it and see where it goes.

**Comment by Darksider3** [comment]
Hey, just started Hacking on. 
How about adding errno from the built-in Python lib to match the Errno-codes as a "dependency"?
(E.g)
```python
Import errno
try:
...
Linking stuff
...
catch OSerror as err:
  if err.errno == errno.$SOME_EXPRESSIONS
     print " something usefull about fixing error based on errno-codes"
```
(Written from mobile, excuse if the codeblack isn't such fancy)

**Comment by anishathalye** [comment]
Hmm, is it better to merely point out what caused the error (e.g. by using https://docs.python.org/2/library/os.html#os.strerror), or should we try to suggest fixes?

I'm not sure if I like suggesting fixes.

(Haha, I didn't know that GitHub did that either! Interesting feature...)

**Comment by Darksider3** [comment]
Hm, yeah. Strerror should be enough :-) 
Im pretty sure that I don't like it. But that was the example how the entire "improvement" would look like. For sure I can easily replace it with the Error-String.
```python
print "Error: %s" %err.strerror
```
That would be enough i think. 
(YEPP, an night sleeping over it changed the mind..^^)

**Comment by anishathalye** [comment]
Also, using strerror allows us to be lazier :P

**Comment by Darksider3** [comment]
+ independent Language(In Linux it was possible to change error-locales provided by the kernel/Bash by installing locales wasn't it?) +Portability(as Windows 10 looks like giving an interface to ELF in the last days)

**Comment by anishathalye** [comment]
Closing due to age / inactivity.
