### ISSUE TITLE
Updating after using init-dotfiles

### ISSUE THREAD

**Issue by brianjking** [anishathalye/dotbot#76]
Hello,

I installed Dotbot with the help of https://github.com/Vaelatern/init-dotfiles. However, it didn't grab all of my dotfiles initially. I've edited the yaml file to add the remainder, how can I get them added to the repo?

Thanks!

**Comment by anishathalye** [comment]
You should be able to move the files from where they are now into your dotfiles repository and track them using git. As an example, take a look at [this](https://github.com/anishathalye/dotfiles).

**Comment by anishathalye** [comment]
Going to assume this is sorted out. If not, feel free to reopen.
