### ISSUE TITLE
Using the latest version (from master) - Can't get "defaults" to work.

### ISSUE THREAD

**Issue by dsifford** [anishathalye/dotbot#79]
Hi there,

I'm having trouble getting "defaults" to work... I keep getting `Action defaults not handled` when running the script.

Here's my `install.conf.yaml`

```yaml
- defaults:
    link:
        create: true
        relink: true

- clean: ['~']

- link:
    /etc/pacman.conf:
        force: true
        path: arch/pacman.conf
    /usr/local/bin/bedroomlights: scripts/bedroomlights
    ~/.bash_profile:
        force: true
        path: bash_profile
    ~/.bashrc:
        force: true
        path: bashrc
    ~/.config/dunst/dunstrc: compiled/dunstrc
    ~/.config/ranger/rc.conf: ranger/rc.conf
    ~/.config/ranger/scope.sh: ranger/scope.sh
    ~/.config/ranger/rifle.conf: ranger/rifle.conf
    ~/.gitconfig: gitconfig
    ~/.git-prompt.sh: scripts/git-prompt.sh
    ~/.i3: i3/config/
    ~/.inputrc: inputrc
    ~/.taskrc: taskrc
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim
    ~/.vimrc: vimrc
    ~/.xinitrc: arch/xinitrc
    ~/.Xresources: arch/Xresources

- shell:
    - [git submodule update --init --recursive, Installing submodules]
```

Let me know if you'd like to have a look at anything else. Thanks in advance. I appreciate the help! :beers:

**Comment by anishathalye** [comment]
Hmm, that config works fine for me. What may be happening is that your `./install` script automatically checks out the last committed (or staged) version of Dotbot, which is the old version.

Try `git submodule update --init --remote dotbot && git add dotbot` and then try running your script. If it works properly, you can commit the new configuration :smile:

**Comment by dsifford** [comment]
You, sir, are a wizard. That worked perfectly :+1: 

Thanks so much for the help!

**Comment by anishathalye** [comment]
Awesome!
