### ISSUE TITLE
Apt-get plugin

### ISSUE THREAD

**Issue by rubenvereecken** [anishathalye/dotbot#80]
Hi, I just tried my hand at a plugin for apt-get, freshly committed to [this repo](https://github.com/rubenvereecken/dotbot-apt-get). I thought it could come in handy to bring along my favorite packages.

Come to think of it, I could have solved it with a separate config file and a rather elaborate shell command that reads from a list from a text file. I was wondering if you thought this could be useful and whether it could be easily improved. I'm rather new to keeping my dotfiles well-organized and value any feedback I can get.

What it can currently do: Tell you which packages failed to install, how many were already available and how many were installed. What should be implemented: Pick specific package versions maybe.

**Comment by anishathalye** [comment]
That certainly looks like it could be useful. Do you use it yourself yet?

Yeah, like you said, I think a lot of people are using just a shell command directly to install packages. I think a plugin could be useful, especially if it does a good job of wrapping the shell command and providing some higher level of abstraction, error checking/correction, etc. (after all, that's what "link" does basically).

By the way, I think some people have worked on a slightly more generic package install command, where it'll use whatever is appropriate for the system (apt-get, brew, pacman, etc.)

**Comment by rubenvereecken** [comment]
Oh have they? Couldn't find any and I really only know barely pacman besides apt-get so I haven't made it more general. I'd be really interested in seeing some other plugins then.

I use it locally (as in, not beyond this one machine) for now. Hoping to see some more use cases pop up while I use it like package updates, which I haven't encountered so far. It's not super pretty to use though since it requires root privileges. I've got a separate `apt-get.conf.yaml` that I can then `sudo ./install -c apt-get.conf.yaml`. Also, my python is installed locally so `sudo` doesn't have the same python binary and packages... it's messy.

Thanks for the feedback.

**Comment by anishathalye** [comment]
Hmm so I thought I've seen people do something like that, but I tried looking for that now for a couple minutes, and I didn't find anything... :/

**Comment by rubenvereecken** [comment]
The amount of plugins seems pretty low anyway. Some advanced searches yielded no results. I wrote a readme and threw in a description so the plugin would show up faster in search results.

I really like dotbot. It took me a while to find a dotfiles manager that suited my basic needs perfectly yet was still extensible enough. What would you think of a little curated plugins list in the README/Wiki? This might convince people even faster to use dotbot.

**Comment by anishathalye** [comment]
I like the idea of having a list of plugins in the Wiki. I just enabled the Wiki for this repo: https://github.com/anishathalye/dotbot/wiki

**Comment by anishathalye** [comment]
https://github.com/anishathalye/dotbot/wiki/List-of-Plugins

**Comment by rubenvereecken** [comment]
Done :smile:! May that list grow and prosper.

I'll take the liberty of closing this issue. Thanks for the fruitful conversation, I'll be happy to add a plugin whenever I think of a possible use case.

**Comment by anishathalye** [comment]
Thanks!
