### ISSUE TITLE
How to run optional installs

### ISSUE THREAD

**Issue by msestak** [anishathalye/dotbot#82]
How can I specify in  .install.conf.yaml "if application is not installed, fetch application from internet and install it, else configure it".
I try to write my .install.conf.yaml idempotent but sometimes if/elsif/else is useful.

**Comment by anishathalye** [comment]
It depends on what OS you're running, which package manager you're using, etc.

If you're using Linux and Apt, `apt-get install`s should be idempotent as it is.

Worst case, you can shell out and use an if/else in the shell command. Or write a plugin.

**Comment by msestak** [comment]
Thank you for your answer. I going to try with `yum install` and if/else logic in shell.
