### ISSUE TITLE
Problem while parsing YAML config

### ISSUE THREAD

**Issue by msestak** [anishathalye/dotbot#83]
I get an error when I run `bash install`:
`Could not read config file:
  mapping values are not allowed here
    in ".install.conf.yaml", line 57, column 152`

Line 57:
`command: sudo perl -le '$/ = undef; open $fh, "+<", "/etc/sudoers"; my $contents = <$fh>; if ($contents =~ /msestak/) {print "msestak ALL= NOPASSWD: ALL already set\n"; } else {print {$fh} "\n#msestak ALL= NOPASSWD: ALL\n";}'`

My guess is that yaml module is parsing : in `NOPASSWD: ALL` as a YAML, and not as a command to execute. Could you limit the parsing done only at the start of line?  Or is there a way to hide : in config from yaml module used here?

Problem is fixed if I remove : in 'NOPASSWD: ALL'.

**Comment by anishathalye** [comment]
This is an issue with YAML parsing, not Dotbot. Look into YAML escaping: http://www.yaml.org/start.html (or a multiline string may work for you).

**Comment by msestak** [comment]
Thank you for your help multiline string worked for me:

    command: >-
      sudo perl -le '$/ = undef; open $fh, "+<", "/etc/sudoers"; my $contents = <$fh>; if ($contents =~   /msestak/) {print "msestak ALL= NOPASSWD: ALL already set\n"; } else {print {$fh} "\nmsestak ALL= NOPASSWD: ALL\n";}'
