### ISSUE TITLE
Support conditional shell commands

### ISSUE THREAD

**Issue by dominicbarnes** [anishathalye/dotbot#88]
It would be great if the commands in `shell` had a cleaner way of only running conditionally. For example, only run if `cmd` is not found in the `$PATH`. I think we could just put such a "check" alongside `stdin`, `stdout` and `stderr`:

```
- shell:
    - command: sudo apt-get install vim
      check: command -v vim
```

Basically, if the command listed in `check` exits with a non-zero, it will proceed to run the `command`. This can be accomplished already with a longer `command`:

```
- shell:
    - [ command -v vim || sudo apt-get install vim, Installing vim ]
```

The first variant is easier to read in my opinion, but since there is a workaround, this proposal is still just a "would-be-nice" at this point.

**Comment by anishathalye** [comment]
Interesting idea. Not sure if enough people need this to warrant the syntactic sugar for it.

One way to get this feature sooner is to write your own plugin (clone the existing `shell.py`, probably will need only a couple lines of code).

**Comment by dominicbarnes** [comment]
Would you be open to a PR?

**Comment by anishathalye** [comment]
In general, I try to avoid adding additional complexity unless there's enough need for it.

**Comment by dominicbarnes** [comment]
That's totally fair, just figured I would ask ;)

**Comment by anishathalye** [comment]
Cool :)

Okay, so I'm gonna close this for now. If there's a compelling reason to include this feature in the future (i.e. we see a bunch of people doing this using the "manual" way), we can re-open the issue.
