### ISSUE TITLE
Create a python package

### ISSUE THREAD

**Issue by gilmrjc** [anishathalye/dotbot#89]
It would be useful to have a package to manage dotfiles outside ~/, something like this (considering you already have a dotfiles repo installed and configured):

```
pip install dotbot
mkdir project
cd project
git init
dotbot --install gitignore-language-template
```

Where the file is inside the dotfiles dir and the install command would copy instead of symlinking. Where is the dotfiles dir? I guess that could be configured inside a dotfile ;)

This would make the dotfiles templating management works for projects outside ~/, which is an nice-to-have feature

**Comment by anishathalye** [comment]
Hm, interesting idea, though I'm not sure this falls within the scope of the Dotbot project.

Have you considered something like [giter8](https://github.com/foundweekends/giter8)?

**Comment by gilmrjc** [comment]
Yes, I use Yeoman to manage project scaffolding but these tools work for that, projects. I think dotbot can manage dotfiles like .gitignore or .editconfig for little projects that don't need a big structure.

One use case I see interesting is creating "teaching repos" where you upload some demo code but have no defined structure. I don't see how I can use Yeoman or giter8 or something alike, but I definitely see an advantage doing dotbot --copy gitignore instead of writing everything from scratch, and I know all the needed rules are there.

Also another really powerful use case is I can create dotfiles and then do something like

```
mkdir new-project-templates
dotbot --install editorconfig
dotbot --install gitignore-specific-language
git init
```

So I can reuse my dotfiles even if I change my project layout, or modify them and just update my templates.

**Comment by gilmrjc** [comment]
Also the dotbot command can link the dotfiles by default, so I can do something like:

```
pip install dotbot
git clone git:my-dotfiles-repo ~/.dotfiles
dotbot
```

Instead of cd ~/.dotfiles && python install.py.

Is this better? Well, I don't know, but for me is a clearer way of using it.

**Comment by anishathalye** [comment]
What's nice is that the current method doesn't require you to `pip install` anything. So you can install your dotfiles on a fresh system without having to do anything else first.

**Comment by gilmrjc** [comment]
Well even in a fresh system I see the package option as something better, but this is just my opinion because I prefer to pip install instead of downloading files. It's easier for me to keep up to date with the project.

## Install dotfiles
If you use dotbot you have python, and surely you have pip, so just do:
```
pip install dotbot
git clone git:my-dotfiles-repo ~/.dotfiles
dotbot
```

In a fresh system I have to do
```
git clone git:my-dotfiles-repo ~/.dotfiles
cd ~/.dotfiles
python ./install.py
```

Almost the same, but more power with the package installed (ok, this is true only if it includes the other options)

## Create dotfiles repo

The initscript can be implemented in python to make this posible:

```
pip install dotbot
dotbot --create
```

With the initscript

```
curl -fsSLO https://raw.githubusercontent.com/Vaelatern/init-dotfiles/master/init_dotfiles.sh
./init_dotfiles.sh
```

**Comment by dsifford** [comment]
Waking this up from the dead, so I apologize for that.

Curious what the rationale is that this doesn't exist as a pip package even for the expected use case? I get that it would require having python and pip installed before being able to use it, but don't most linux-based OS'es have that baked in by default?

The reason why I'd be interested in this is because submodules are sort of a nightmare to work with. It would be much easier to just `pip install --upgrade dotbot` rather than have to worry myself with keeping the submodule up to date, etc.

Thanks for clarifying :blush:

**Comment by anishathalye** [comment]
Hmm, true.

Okay, I'll do it! Will probably have time sometime in the next week or so.

**Comment by paride** [comment]
This would also ease the downstream packaging of dotbot (I'm thinking of maintaining a Debian dotbot package). I really hope the feature lands.

The `dotbot` script would have to rewritten to use the system-wide installed libraries, but it should be doable.
