### ISSUE TITLE
Feature Request: GPG encrypted files

### ISSUE THREAD

**Issue by Anachron** [anishathalye/dotbot#92]
@I've made this quick and dirty hack to allow gpg encrypted files to be automatically decrypted and added to my .gitignore (if not blacklisted yet).

The script also checks if the file has been decrypted already.

``` bash
#!/usr/bin/env bash

# =======================================
# Encrypt and decrypt files based on gpg
# =======================================
# 
# Howto:
# Create a file, for example test, inside the main directory.
# Now encrypt it using gpg (like 'gpg -o test.enc.gpg -r <IDENTITY> -e test')
# And run this script. 
# The script will find all files ending with .enc.gpg and tries to find it's decrypted file counterpart.
# If the decrypted file is not in the .gitignore file it will be added.
# Further changes to the decrypted file will automatically be transfered to the encrypted file.
# In case there is no decrypted version, the script will also decrypt it itself.
# If the encrypted file is newer than the decrypted one, it will decrypt again.

set -e
shopt -s globstar

# If no GPG ID available in ENV, take the first private identity that we have
[[ "${GPG_ID}" == '' ]] && GPG_ID=$(gpg -K 2>/dev/null | grep -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b" | head -n 1)

# If at this point we don't have a GPG identity, exit
[[ "${GPG_ID}" == '' ]] && exit 1

function decFile(){
  gpg -q -d "${1}" 2>/dev/null > "${2}"
}

function encFile(){
  #echo "[INFO] Encrypting \"${1}\" to \"${2}\""
  gpg -q -o "${2}" -r "${GPG_ID}" -e "${1}" 2>/dev/null
}

function ts2Str(){
  date -d @"${1}" +%Y%m%d%H%M.%S
}

for encName in **/*.enc.gpg; do
  [[ ! -f "${encName}" ]] && continue
  encModified=$(stat -c %Y "${encName}")
  decName="${encName%.enc.gpg}"
  if [[ ! -f "${decName}" ]]; then
    echo "[INFO] Decrypting \"${1}\" to \"${2}\""
    decFile "${encName}" "${decName}"
    touch -mt $(ts2Str ${encModified}) "${decName}"
  else
    decModified=$(stat -c %Y "${decName}")
    if [[ "${decModified}" -gt "${encModified}" ]]; then
      echo "[INFO] Decrypted file \"${decName}\" has changed."
      encFile "${decName}" "${encName}"
      touch -mt $(ts2Str ${decModified}) "${encName}"
    elif [[ "${encModified}" -gt "${decModified}" ]]; then
      echo "[INFO] Encrypted file \"${encName}\" has changed."
      decFile "${encName}" "${decName}"
      touch -mt $(ts2Str ${encModified}) "${decName}"
    fi
  fi
  if [[ ! $(git check-ignore "${decName}") ]]; then
    echo "[INFO] Ignoring \"${decName}\""
    echo -en "\n${decName}" >> '.gitignore'
  fi
done
```

Maybe it would be helpful for someone?

**Comment by anishathalye** [comment]
Pinging @bbenne10 and @dwhoban talked about it here: https://github.com/anishathalye/dotbot/issues/35#issuecomment-216308469

**Comment by Anachron** [comment]
Wow that's a quick reply! Basically files having the extension *.enc.gpg will be looked for and one would only have to add that to the dotbot shell section.

**Comment by anishathalye** [comment]
Email notifications are great 😄 

In any case, we can add this to the [wiki](https://github.com/anishathalye/dotbot/wiki/Tips-and-Tricks), and keep the issue open while we're thinking about the feature request.

**Comment by Anachron** [comment]
I will try to mess more with my script to make it more solid. For now it's a very simple way how to do it. (All that I need for now)

**Comment by bbenne10** [comment]
Ill clone and test this out this evening! This looks pretty cool.

**Comment by Anachron** [comment]
@bbenne10 I updated it slighty to use `git check-ignore` now instead

**Comment by xen0l** [comment]
Having this feature ootb would be nice.

**Comment by ashyon** [comment]
+1 to this feature. really would be great.

**Comment by anishathalye** [comment]
I wonder if it could first be done as a plugin (and then maybe incorporated into the core distribution at some point)?

**Comment by sobolevn** [comment]
You can use something like [`git-secret`](https://github.com/sobolevn/git-secret) or `blackbox` to handle that.

**Comment by anishathalye** [comment]
Closing due to age/inactivity; not planning on implementing this feature in the core library.

This plugin implements related functionality: https://gitlab.com/gnfzdz/dotbot-gitcrypt

**Comment by fcatuhe** [comment]
For anyone still looking for this — I've built [dotbot-age](https://github.com/fcatuhe/dotbot-age), a plugin that solves this using [age](https://github.com/FiloSottile/age) encryption (a modern, simpler alternative to GPG).

It works with a `decrypt` directive:

```yaml
- plugins:
    - dotbot-age

- decrypt: true

- link:
    ~/.ssh/config: private/ssh/config
```

The approach:
- Secrets are stored as `KEY=VALUE` in an age-encrypted file (`encrypted/secrets.env.age`)
- Template files in `encrypted/` use `{{PLACEHOLDER}}` syntax
- The plugin renders them into `private/` (gitignored) with proper permissions (700 dirs, 600 files)
- It's idempotent, supports `--dry-run`, and follows conventions so zero config is needed

It also ships with an `edit-secrets` script that decrypts, opens your `$EDITOR`, re-encrypts on save, and re-renders templates — no need to re-run `./install` since symlinks already point to `private/`.
