### ISSUE TITLE
update "Get Running in 5 Minutes" to contemplate starting from scratch

### ISSUE THREAD

**Issue by bjacobowski** [anishathalye/dotbot#94]
As someone not familiar with submodules, it took me a minute to figure out why adding the submodule wasn't working...a submodule must be sub to something. You need to initialize your ~/.dotfiles repo before trying to add a submodule.
```bash
#mkdir ~/.dotfiles # create dotfiles directory if starting from scratch
cd ~/.dotfiles # replace with the path to your dotfiles
#git init # initialize dotfiles repository if needed
git submodule add https://github.com/anishathalye/dotbot
cp dotbot/tools/git-submodule/install .
touch install.conf.yaml
```

**Comment by anishathalye** [comment]
I'm not sure if this is necessary. That section does say "If you're using Git, you can add Dotbot as a submodule". I think the "using Git" part implies that you've initialized the Git repo. And if you haven't, this message is pretty helpful:

```
$ git submodule add https://github.com/anishathalye/dotbot
fatal: Not a git repository (or any of the parent directories): .git
```

So people will probably be able to figure it out.

**Comment by bjacobowski** [comment]
No, it isn't necessary if you already have a repo; but it's necessary if
you're starting from scratch. When you say "using Git," I was thinking
using git in general, ie "git is installed." And although I've used git for
years, I'm not sure I've ever used a submodule directly. So when I first
saw the error message, I thought it was referring to the target (that I had
misspelled the link or something).

You're right that people will figure it out, in hindsight it's
obvious...but what's the downside to writing your tutorial from the
perspective of someone starting from scratch? It might have taken me 3
minutes to figure out what was going wrong, not a big deal...but when I'm
trying out a new project, it's really annoying to get sidetracked on stupid
stuff unrelated to the project itself.

I provided my feedback because I like your project, didn't think my
experience would be unique, and the solution is so simple. If you disagree,
that's fine.

**Comment by anishathalye** [comment]
Ah, okay, that makes sense :)
I hadn't thought about it from the point of view of people who are _planning on_ using Git but haven't initialized their repo yet. And yeah, you're right, I actually think the couple minutes of being sidetracked have a huge impact on adoption and stuff.

Thanks for the feedback!

Fixed in f04b94d4ae98599568d868c6d14d2ea428d4f16a (you're credited in the commit message).

**Comment by bjacobowski** [comment]
Cool and thanks, I really like my new setup!

**Comment by anishathalye** [comment]
Awesome :)

Okay, I'm gonna close this issue, feel free to open more if anything else comes up.
