### ISSUE TITLE
Feature request: symlink target dir

### ISSUE THREAD

**Issue by QiangF** [anishathalye/dotbot#95]
Hello,
There are two use cases.
1 currently dotbot presumes all setting files are in the dotfile repo, but some settings of mine that are constantly changing, like the firefox profile folder, it is synced with dropbox and not placed in my dotfiles git repo, so I can't use the link mechanism to make the symlink and have to use shell commands. 
2 some settings that are confidential, so they are not in the dotfiles repo and have to use shell commands too.
So I am suggesting replacing the "- link" keyword with the basedir of the symlink targets, so dotbot will find my settings outside dotfiles repo.
Thank you!

**Comment by anishathalye** [comment]
You can already link files outside your dotfiles repository. You can already use stuff like:

```yaml
- link:
    ~/Library/Preferences/Firefox: ~/Dropbox/Configs/Firefox
```

**Comment by QiangF** [comment]
Thank you!

**Comment by QiangF** [comment]
I tried with the latex git version, and got "nonexisting target" error, dotbot still tries to add the basedir prefix to the symlink target path.

**Comment by anishathalye** [comment]
Could you please send me a minimal failing test case that I can reproduce so I can debug this?

**Comment by QiangF** [comment]
My dotfiles path: ~/.dotfiles
dotbot path: ~/.dotfiles/dotbot
I didn't change the install script,~/.dotfiles/install contains

    #!/usr/bin/env bash

    set -e

    CONFIG="install.conf.yaml"
    DOTBOT_DIR="dotbot"

    DOTBOT_BIN="bin/dotbot"
    BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    cd "${BASEDIR}"

    (cd "${DOTBOT_DIR}")
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

you can try install.conf.yaml with content like you suggested.

    - link:
        ~/Library/Preferences/Firefox: ~/Dropbox/Configs/Firefox

dotbot will try to add ~/.dotfiles to ~/Dropbox/Configs/Firefox

**Comment by QiangF** [comment]
Maybe adding a rule: if the symlink target path beginnes with ~, don't add the basedir prefix.

**Comment by anishathalye** [comment]
Ohhhh, so this is the issue: see #93.

Do you think this is unintuitive? Should we `os.path.expanduser()` on both the source and the destination of the link?

**Comment by QiangF** [comment]
Thank you for the link. I should set relative to false or use the $HOME variable.

**Comment by anishathalye** [comment]
By the way, 28959a3f31d8632975de4e18d0a0e47476b5a413 makes it so you can use `~/whatever` on the right hand side of the link.

(CC @Lindenk from #93)
